= Identity Assertion
:toc: macro
:toc-title:
:sectanchors:
:sectnums!:

The https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html[*C2PA technical specification*] allows _<<_actor,actors>>_ in a workflow to make cryptographically signed _<<_c2pa_assertion,assertions>>_ about the produced _<<C2PA asset>>._ This signature is issued by the vendor whose software or hardware was used to create the assertions and the claim, which is why it is called the _claim generator._

This specification describes a _<<C2PA assertion>>_ referred to here as the *identity assertion* that can be added to a _<<C2PA Manifest>>_ to enable a _<<_credential_subject,credential subject>>_ to prove control over a digital identity and to use that identity to document their role in the _<<C2PA asset>>’s_ lifecycle.

*Preliminary draft 30 November 2023* +
xref:_version_history[]

IMPORTANT: This is an early private review draft of this document. Please refer to the draft date above when providing feedback. See xref:_version_history[] for description of what has changed between private review drafts.

*Editors:*

* mailto:scouten@adobe.com[Eric Scouten] (https://adobe.com[Adobe])

include::partial$toc.adoc[]
include::partial$status.adoc[]
include::partial$license.adoc[]

:sectnums:

== Introduction

_This section is non-normative._

=== Design goals

This specification aims to allow _<<_credential_subject,credential subjects>>_ to document their involvement in _<<_c2pa_asset,C2PA assets>>_ produced by them or on their behalf, and _<<_c2pa_manifest_consumer,consumers>>_ of those _<<_c2pa_asset,C2PA assets>>_ to independently verify that those received _<<_c2pa_asset,C2PA assets>>_ were in fact produced by the named _<<_credential_subject,credential subjects>>_ and have not been tampered with.

It accomplishes this by drawing upon and extending existing work from two standards organizations.

=== C2PA technical specification

The https://c2pa.org[Coalition for Content Provenance and Authenticity (C2PA)] has developed a https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html[technical specification] for providing content provenance and authenticity. It is designed to enable global, opt-in, adoption of digital provenance techniques through the creation of a rich ecosystem of digital provenance enabled applications for a wide range of individuals and organizations while meeting appropriate security requirements.

The C2PA technical specification allows other standards bodies to define additional metadata that can be incorporated into a _<<C2PA Manifest>>._ These statements come in the form of a _<<_c2pa_assertion,C2PA assertion>>._

This specification describes a specific _<<C2PA assertion>>_ that can be added to a _<<C2PA Manifest>>_ which allows a _<<_credential_subject,credential subject>>_ to prove control over an digital identity and bind that identity to a _<<_c2pa_asset,C2PA asset>>_ produced by them or on their behalf.

=== Trust over IP technical architecture

The https://trustoverip.org[Trust over IP Foundation (ToIP)] has developed a https://github.com/trustoverip/TechArch/blob/main/spec.md[technical architecture specification] for describing a decentralized digital trust infrastructure.

NOTE: This specification refers to a “public review draft” of the ToIP technical architecture specification published on 14 November 2022 which is current as of the writing of this specification.

The ToIP architecture specification introduces the concept of _<<_toip_verifiable_identifier,verifiable identifier>>_ as follows:

> Design Principle #5 (https://trustoverip.org/permalink/Design-Principles-for-the-ToIP-Stack-V1.0-2022-11-17.pdf[Cryptographic Verifiability]) states that “messages and data structures exchanged between parties should be verifiable as authentic using standard cryptographic algorithms and protocols”. This requires that Endpoint Systems be able to associate, discover and verify the cryptographic keys associated with a ToIP identifier. This specification will refer to identifiers that meet this basic requirement of cryptographic verifiability as verifiable identifiers (VIDs).
-- https://github.com/trustoverip/TechArch/blob/main/spec.md#64-toip-identifiers[Section 6.4: ToIP identifiers]

NOTE: The ToIP definition of the term “verifiable identifier” is well-aligned with the design goals of this specification. As of this writing, ToIP has just begun the process of producing a technical standard that describes how to _implement_ verifiable identifiers. This specification will incorporate relevant technical standards for verifiable identifiers as they become available.

This specification describes mechanisms to support two common individual and organizational identity mechanisms that fit the conceptual description of _<<ToIP verifiable identifier>>:_

* https://www.w3.org/TR/did-core/[Distributed identifiers (DIDs)] as defined by W3C, though support will be limited to specifically-chosen DID methods with wide adoption and independent verifiability.
* https://tools.ietf.org/html/rfc5280[X.509 certificates]

== Glossary

=== Concepts adapted from C2PA technical specification

The following definitions are adapted from the link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_glossary++[glossary] provided in the C2PA technical specification. This specification uses the prefix “C2PA” to denote data structures incorporated from that specification.

==== Actor

A human or non-human (hardware or software) that is participating in the C2PA ecosystem. For example: a camera (capture device), image editing software, cloud service or the person using such tools.

NOTE: An organization or group of _actors_ may also be considered an _actor_ in the C2PA ecosystem.

NOTE: TO DO: Track upcoming definition change in C2PA spec.

==== C2PA asset

A file or stream of data containing _digital content,_ _asset metadata,_ and a <<C2PA Manifest>>.

For the purposes of this definition, we will extend the typical definition of “file” to include cloud-native and dynamically generated data.

IMPORTANT: The definition of “C2PA asset” in this specification differs from the definition of “asset” given in the C2PA technical specification. A “C2PA asset” as defined in _this_ specification MUST contain a <<C2PA Manifest>>.

==== C2PA Manifest

The set of information about the _provenance_ of a _<<C2PA asset>>_ based on the combination of one or more _<<_c2pa_assertion,C2PA assertions>>_ (including content bindings), a single _<<C2PA claim>>,_ and a _claim signature._ A _C2PA Manifest_ is part of a _C2PA Manifest Store._

NOTE: A _C2PA Manifest_ can reference other _C2PA Manifests._

See link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_manifests++[Section 12, “Manifests,”] of the C2PA technical specification.

==== C2PA claim

A digitally signed and tamper-evident data structure that references a set of _<<_c2pa_assertion,assertions>>_ by one or more _<<_actor,actors>>,_ concerning a _<<C2PA asset>>,_ and the information necessary to represent the content binding. If any _<<_c2pa_assertion,C2PA assertions>>_ were redacted, then a declaration to that effect is included. This data is a part of the _<<C2PA Manifest>>._

See link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_claims++[Section 11, “Claims,”] of the C2PA technical specification.

==== C2PA assertion

A data structure which represents a statement asserted by an _<<_actor,actor>>_ concerning the _<<C2PA asset>>._ This data is a part of the _<<C2PA Manifest>>._

See link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_assertions++[Section 6, “Assertions,”] of the C2PA technical specification.

==== C2PA Manifest Consumer

An _<<_actor,actor>>_ who consumes a _<<_c2pa_asset,C2PA asset>>_ with an associated _<<C2PA Manifest>>_ for the purpose of obtaining the provenance data from the _<<C2PA Manifest>>._

NOTE: When this _<<_actor,actor>>_ is concerned with validating the identity assertions contained within a _<<C2PA Manifest>>,_ this role can also be thought of as a *relying party* or *verifier* as defined in specifications such as the link:++https://www.w3.org/TR/vc-data-model/#dfn-verifier++[W3C verifiable credentials data model].

=== Concepts adapted from ToIP technical architecture

The following definitions are adapted from the link:++https://github.com/trustoverip/TechArch/blob/v1-PR1/spec.md++[Trust over IP (ToIP) technology architecture specification]. This specification uses the prefix “ToIP” to denote concepts incorporated from that specification.

==== ToIP verifiable identifier

Any identifier for which an endpoint system is “able to associate, discover and verify the cryptographic keys associated with a ToIP identifier.” This satisfies the ToIP design principle that “messages and data structures exchanged between parties should be verifiable as authentic using standard cryptographic algorithms and protocols.”

See link:++https://github.com/trustoverip/TechArch/blob/v1-PR1/spec.md#64-toip-identifiers++[ToIP identifiers] in the ToIP technology architecture specification.

=== Concepts specific to this specification

==== Credential subject

An _<<_actor,actor>>_ that is identified by a _<<ToIP verifiable identifier>>._

==== Partial claim

A _<<C2PA claim>>_ with specific data fields blanked out because the content of the *identity assertion* has not yet been determined.

See xref:_partial_claim_definition[xrefstyle=full] for details on how to calculate this assertion.

== Normative references

* https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html[C2PA technical specification]
* https://www.w3.org/TR/vc-data-model/[W3C verifiable credentials data model]
* https://www.w3.org/TR/did-core/[W3C distributed identifiers (DIDs)]
* https://tools.ietf.org/html/rfc5280[Internet X.509 public key infrastructure certificate] (RFC 5280)

include::partial$terms.adoc[]
include::partial$version_history.adoc[]

== Assertion definition

=== Overview

Each identity assertion instance allows exactly one _<<_credential_subject,credential subject>>_ to sign an adapted version of the _<<_c2pa_claim,C2PA claim>>_ data structure known as a _<<_partial_claim,partial claim>>._

The derivation of a _<<_partial_claim,partial claim>>_ is explained in xref:_partial_claim_definition[xrefstyle=full].

The identity assertion contains the following data fields:

* `signature` contains the raw byte stream of the _<<_credential_subject,credential subject>>’s_ signature
* `sig_type` defines the data type of signature
* `pad1` and `pad2` are zero-filled byte strings used to fill space

The content of `signature` depends on the type of credential that is used. Valid credential types and the corresponding `signature` data structures and `sig_type` values are explained in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

The identity assertion shall have a label of `cca.identity`. More than one identity assertion may appear in a _<<C2PA claim>>;_ if this occurs, these assertions shall be given unique labels as described by link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_multiple_instances++[Section 6.4, “Multiple instances,”] of the C2PA technical specification.

NOTE: Describe how to allow actors to describe their role in the content (previously described via CreativeWork assertion) and potentially in specific steps referenced in C2PA actions assertion.

NOTE: TO DO: Where would things like social media accounts live? Or should that be a separate assertion?

=== Schema and example

The schema for this type is defined by the `identity` rule in the following https://datatracker.ietf.org/doc/html/rfc8610[CDDL definition]:

[source,cddl]
----
identity = {
  "sig_type": tstr .size (1..max-tstr-length), ; A string identifying the data type of the signature field that follows. If the value of this string is not declared in this specification under (TO DO), this structure is invalid.
  "signature": bstr, ; byte string of the signature
  "pad1": bstr, ; zero-filled byte string used for filling up space
  ? "pad2": bstr, ; optional zero-filled byte string used for filling up space
}
----

An example in https://www.rfc-editor.org/rfc/rfc8949.html#name-diagnostic-notation[CBOR-Diag] is shown below:

[source,json]
----
xxx
----

NOTE: TO DO: Prepare example.

=== Partial claim definition

It is necessary to resolve a circular dependency issue involving the following relationships:

* A _<<C2PA claim>>_ must reference at least one _content binding assertion_ which provides a tamper-evident link from the _<<C2PA claim>>_ to the _<<C2PA asset>>._ For many asset file formats, it is necessary to finalize the file layout in order to correctly create the content binding assertion.
* The identity assertion contains a signature over the _<<C2PA claim>>_ issued by a _<<_credential_subject,credential subject>>._
* A _<<C2PA claim>>_ references its _<<_c2pa_assertion,C2PA assertions>>_ by hashed URIs.

In order to break the circular dependency between the _<<C2PA claim>>_ and the _<<_c2pa_assertion,C2PA assertions>>_ listed above, this specification introduces the concept of *partial claim.*

A *partial claim* MUST contain the exact CBOR serialization as the corresponding final _<<C2PA claim>>,_ except that for each identity assertion referenced in the claim, the `hash` field of the hashed URI entry MUST be replaced with an equivalent number of zero bytes.

The CBOR serialization of the *partial claim* is presented as the content to be signed by the _<<_credential_subject,credential subject>>._

== Creating the identity assertion and claim

=== Claim creation overview

The C2PA technical specification defines a specific sequence of steps to perform in link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_creating_a_claim++[Section 11.3, “Creating a claim.”] When creating a _<<C2PA claim>>_ with one or more identity assertions, that sequence MUST be performed as described in the C2PA technical specification with additional steps as described below:

1. link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_creating_assertions++[Section 11.3.1, “Creating assertions.”] Any identity assertion that will be added to the claim MUST be represented during this step by a placeholder assertion as described in xref:_creating_placeholders_for_identity_assertions[xrefstyle=full] during this step.
2. link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_adding_assertions_and_redactions++[Section 11.3.2.1, “Adding assertions and redactions”]
3. link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_adding_ingredients++[Section 11.3.2.2, “Adding ingredients”]
4. link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_connecting_the_signature++[Section 11.3.2.3, “Connecting the signature”]
5. If the link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_multiple_step_processing++[multiple step processing (Section 11.4)] process is being used, the following steps from that workflow MUST be completed before proceeding:
** link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_prepare_the_xmp++[Section 11.4.1, “Prepare the XMP”] NOTE: Track possible upcoming change in C2PA spec regarding XMP.
** link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_create_content_bindings++[Section 11.4.2, “Create content bindings”]
6. A _<<_partial_claim,partial claim>>_ MUST be computed at this time as defined in xref:_partial_claim_definition[xrefstyle=full]. This _<<_partial_claim,partial claim>>_ MUST be presented to the _<<_credential_subject,credential subject>>_ for each identity assertion to be added, as described in xref:_presenting_the_partial_claim_for_signature[xrefstyle=full] by the corresponding _<<_credential_subject,credential subject>>._ Once each signature has been obtained, the placeholder assertion content MUST be replaced with the final assertion content incorporating that signature.
7. Convert the _<<_partial_claim,partial claim>>_ to the final _<<c2pa-claim,C2PA claim>>_ as described in xref:_generating_the_final_claim[xrefstyle=full].
8. If the link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_multiple_step_processing++[multiple step processing (Section 11.4)] process is being used, the remaining steps from that workflow MUST be completed. The remaining steps MUST NOT be performed sooner than this stage in the overall process.
9. link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_signing_a_claim++[Section 11.3.2.4, “Signing a claim”]
10. link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_time_stamps++[Section 11.3.2.5, “Time stamps”]
11. link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_credential_revocation_information++[Section 11.3.2.6, “Credential revocation information”]

These steps are also represented by the following sequence diagram, which is non-normative.

[mermaid,width=100%]
....
sequenceDiagram
    participant G as Claim generator
    participant H as Credential holder

    G->>G: Create assertions
    Note right of G: Includes identity placeholder assertions
    G->>G: Create content bindings
    G->>G: Create partial claim

    loop For each credential holder
    G->>H: Request signature over partial claim
    H->>G: Provide signature over partial claim
    end

    G->>G: Replace placeholder assertions with final identity assertions
    G->>G: Create final claim
    G->>G: Issue claim generator signature for final claim
    G->>G: Create manifest store
....

=== Creating placeholders for identity assertions

As per link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_creating_assertions++[Section 11.3.1, “Creating assertions,”] of the C2PA technical specification, all assertions must be created and stored in a newly-created assertion store.

A temporary version of the identity assertion, referred to as a *placeholder assertion,* is created to reserve space for the _<<_credential_subject,credential subject>>’s_ signature which will be added later.

This enables the final layout of the _<<C2PA asset>>_ to be computed, which then enables a valid _content binding assertion_ to be computed. A valid content binding assertion is critical to binding the _<<C2PA Manifest>>_ to the _<<C2PA asset>>_ which also enables binding the _<<_credential_subject,credential subject>>_ to the _<<C2PA asset>>._

A placeholder assertion MUST have its `sig_type` field set to `cca.placeholder`. The `signature` field MUST be set to a zero-length byte array. The `pad1` and `pad2` fields MUST be filled with enough zero-value (`0x00`) bytes to leave sufficient room for the `signature` value that will be added later.

IMPORTANT: The `sig_type` value of `cca.placeholder` is not valid when present in a final, signed _<<C2PA Manifest>>._

IMPORTANT: The size of the final identity assertion MUST exactly match the size of the placeholder assertion created at this time. Therefore, the `pad1` and `pad2` fields of a placeholder assertion MUST be sufficiently large to reflect any possible size of the final assertion.

=== Presenting the partial claim for signature

The serialized CBOR of the _<<_partial_claim,partial claim>>_ document at this stage MUST now be presented as the payload to be signed by the credential holders corresponding to each identity assertion.

The signature method will depend on the nature of credential presented. These are described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

Once the signatures are obtained, the content of each identity assertion previously added to the _<<C2PA claim>>_ MUST be replaced with new assertion content where the `sig_type` and `signature` value correctly bind the _<<_credential_subject,credential subject>>_ to the content. The acceptable values for these fields depend on the nature of credentials used and are described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full]. Now that the `signature and `sig_type` values are available, the values of the `pad1` and `pad2` MUST be recomputed (reduced in size) such that the resulting identity assertion exactly matches the size of the placeholder assertion.

NOTE: Preferred/deterministic CBOR serialization of byte arrays uses a variable-length integer to specify the length of the encoded binary data. When the length goes from zero to one byte, or one to two bytes (etc.), the length of the resulting pad jumps by two bytes. This means that not all paddings can be expressed using a single padding field. For example, 24-byte and 26-byte pads can be created, but a 25-byte pad cannot. If this situation arises, the desired padding can be split between `pad1` and `pad2`. For example, to make a 25-byte pad, an implementation can encode 19 bytes into `pad1` (resulting in an encoded length of 20 bytes), and 4 bytes into `pad2` (resulting in 5 bytes.)

If the signature exceeds the space available in the identity assertion, the claim generation process MUST be repeated with a larger padding size chosen in the xref:_creating_placeholders_for_identity_assertions[xrefstyle=full] step.

=== Generating the final claim

The final _<<C2PA claim>>_ data structure MUST now be computed by replacing the hashed URI references for identity assertions in the _<<_partial_claim,partial claim>>_ with correct values for the `hash` field for each now-updated assertions.

IMPORTANT: The final claim MUST contain the exact CBOR serialization as the corresponding _<<_partial_claim,partial claim>>,_ except for the `hash` updates as just described.

== Validating the identity assertion

An identity assertion is valid only if the _<<C2PA Manifest>>_ in which the assertion is contained is valid as defined by the section titled link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_validation++[Section 16, “Validation,”] of the C2PA technical specification. Validation of the _<<C2PA Manifest>>_ MUST be completed with a successful result before a validator attempts to report on the validity of an identity assertion.

=== Validation method

An identity assertion MUST contain valid CBOR that satisfies the `identity` rule in xref:_schema_and_example[xrefstyle=full]. The `cca.identity.cbor.invalid` error code SHALL be used to report assertions that do not follow this rule.

The `pad1` and `pad2` fields of an identity assertion MUST contain only zero bytes. The `cca.identity.pad.invalid` error code SHALL be used to report assertions that contain other values in these fields.

The `sig_type` field of an identity assertion MUST contain one of the values described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full]. The `cca.identity.sig_type.invalid` error code SHALL be used to report assertions that contain unrecognized values.

The validator MUST compute the _<<_partial_claim,partial claim>>_ as described in xref:_partial_claim_definition[xrefstyle=full]. The validator MUST also follow all validation rules for the signature type declared in the `sig_type` field as described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full], using the value of _<<_partial_claim,partial claim>>_ just calculated.

=== Status codes

The set of standard success and failure codes for identity assertion validations are defined below. These follow the format defined by the section titled link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_status_codes++[Section 16.1, “Status codes,”] of the C2PA technical specification.

The `url` field for a status code MUST always be the label of the identity assertion. It is omitted from the tables below.

==== Success codes

[width="100%",cols="4,10",options="header"]
|=======================
| Value        |   Meaning
|`cca.identity.validated` | The identity assertion, including the referenced credentials and signature binding the credential holder to the _<<C2PA claim>>_, is validated.
|=======================

==== Failure codes

[width="100%",cols="4,10",options="header"]
|=======================
| Value        |   Meaning
|`cca.identity.cbor.invalid` | The CBOR of the identity assertion is not valid.
|`cca.identity.sig_type.invalid` | The `sig_type` of the identity assertion is not valid.
|`cca.identity.pad.invalid` | The `pad1` or `pad2` field contains non-zero bytes.
|=======================

NOTE: Additional failure codes relating to specific signature types are defined in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

== Credentials, signatures, and validation methods

The identity assertion allows multiple signature types to be represented, although only one _<<ToIP verifiable identifier>>_ and corresponding signature can be used in any single assertion.

The signature type is represented by the `sig_type` field and must be one of the values described within this section.

=== W3C verifiable credentials and verifiable presentations

In some use cases, an _<<_actor,actor>>_ in the system may wish to provide its own _https://www.w3.org/TR/vc-data-model/[W3C verifiable credential],_ as it exists at that moment in time, to the _claim generator_ to have it associated with one or more _<<_c2pa-assertion,C2PA assertions>>._ This _<<_actor,actor>>_ may be an individual, group, or organization.

NOTE: TO DO: Above comment about association with assertion is adapted from C2PA spec. Is it still correct to tie identity _only_ to _assertions_ or can it also be more generally to a _claim_ or _asset?_

The _<<_actor,actor>>_’s _verifiable credential_ is combined with a _verifiable credential_ for the _<<C2PA claim>>_ into a _link:++https://www.w3.org/TR/vc-data-model/#presentations-0++[W3C verifiable presentation]._

NOTE: Discuss whether the VC for the claim is necessary. I’ve heard some feedback that having a VC for the claim would make it easier for a wallet application to have suitable information to present when fulfulling the presentation request. A counter-concern is that this is effectively redundant and would require the claim-generator’s identity to be expressed both in X.509 and VC. Need to balance these concerns.

The `sig_type` value for such an assertion MUST be `org.w3.verifiable_presentation` and the `signature` value MUST be the _verifiable presentation_ serialized as described in link:++https://www.w3.org/TR/vc-data-model/#json-ld++[Section 6.2, “JSON-LD,”] of the W3C verifiable credentials data model spec.

NOTE: TO DO: Is JSON-LD still required/preferred? I’ve heard some feedback that there may be less consensus around this now.

NOTE: JSON-LD serialization is mandated as it is the most commonly used of the three syntaxes presented in link:++https://www.w3.org/TR/vc-data-model/#syntaxes++[Section 6, “Syntaxes,”] of the W3C verifiable credentials specification. It is also the one that aligns best with its extensibility model, which could be useful to some implementers.

==== Verifiable credential for actor

NOTE: TO DO: Reconsider the following statement from C2PA 1.3 spec. Since we’re shifting to verifiable presentations, I think we want to make a stronger statement to indicate that the actor _did_ authorize the claim.

[quote]
____
W3C verifiable credentials are used in this specification to decorate the actors identified in assertions with more information, potentially providing additional trust signals. Although these W3C verifiable credentials can include proofs of their own authenticity, they are *not* a mechanism for verifying that a particular actor authorised a claim, assertion or piece of metadata. Any validation or usage of the W3C cerifiable credential is out of scope of this specification and has no bearing on the link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_trust_model++[C2PA Trust Model].

For example, conveying a W3C verifiable credential for the actor identified as the `author` in an assertion might link that author’s ID with an email address, social media ID, or real name, or it might identify that actor as a member of a particular professional body, or provide other qualifications relevant to the actor’s involvement in the asset.
____

NOTE: TO DO: Build a new example of a compliant credential.

A _verifiable credential_ used with an identity assertion MUST contain only a single `credentialSubject` and that `credentialSubject` shall have an `id` value, which MUST be a valid _https://www.w3.org/TR/did-core/[W3C decentralized identifier]._

As defined in link:++https://www.w3.org/TR/did-core/#methods++[Section 8, “Methods,”] of the W3C decentralized identifier spec, a _DID method_ defines how implementers can create, resolve, update, and deactivate DIDs and DID documents.

All _W3C distributed identifiers_ that are stored in an identity assertion SHALL be generated using one of the _DID methods_ as described in this section. This section defines both:

* A list of _DID methods_ that are allowed for generating identifiers for new content as well as required for validating identifiers of existing content (the allowed list), and
* A list of _DID methods_ that are required to be supported for validating identifiers of existing content but are not allowed for generating identifiers for new content (the deprecated list).

A _DID method_ MUST appear in no more than one list. If a DID method does not appear in either list, it is forbidden and MUST NOT be used or supported. Algorithms can be removed from the lists in order to implement forbidding an algorithm. For this reason, implementations MUST NOT support additional algorithms on an optional basis.

NOTE: TO DO: Is the strict prohibition necessary in this case?

Implementers SHOULD consult this section in the current version of the specification when releasing software updates and ensure their supported algorithms conform to it.

The allowed list is:

* https://w3c-ccg.github.io/did-method-web/[`did:web`]
* https://trustoverip.github.io/tswg-did-method-webs-specification/[`did:webs`]

The deprecated list is empty.

==== Credential security considerations

NOTE: TO DO: Review the following statement adapted from C2PA spec. I think it’s at odds with the use of DID documents, and should likely be removed.

> In most W3C verifiable credential workflows, the information about the subject (e.g., the cryptographic keys) is fetched on demand at the time of validation. While that is an acceptable model, it does open up a possible attack vector by providing an attacker with an externally-visible signal about what the validator is validating. Therefore, this specification also supports having the information captured and embedded at the time of signature. This not only prevents leakage, but also makes it very clear what data the signer is asserting about the credential’s subject. 

==== Verifiable credential for claim

NOTE: TO DO: Describe how to create VC for claim. Depends on outcome of TO DO item earlier regarding whether this VC is necessary.

==== Verifiable presentation

NOTE: TO DO: Describe how to create the VP from the above two claims.

==== Verifying the verifiable presentation

NOTE: TO DO: Write up verification procedures.

=== X.509 certificates and COSE signatures

In some use cases, an _<<_actor,actor>>_ in the system may wish to provide an _https://tools.ietf.org/html/rfc5280[X.509 certificate]_ to have an organizational or individual identity described by the certificate associated with the _<<C2PA claim>>._

The `sig_type` value for such an assertion MUST be `org.ietf.cose`. The `signature` value MUST be a _https://datatracker.ietf.org/doc/html/rfc8152[COSE signature]_ as described below.

==== Generating the COSE signature

To generate the COSE signature for an identity assertion, the steps described in the listed sections of the C2PA technical specification MUST be followed with adaptations as described subsequently:

* link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_signing_a_claim++[Section 11.3.2.4, “Signing a claim”]
* link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_time_stamps++[Section 11.3.2.5, “Time-stamps”]
* link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_credential_revocation_information++[Section 11.3.2.6, “Credential revocation information”]
* link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_hashing_2++[Section 14.1, “Hashing”]
* link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_digital_signatures++[Section 14.2, “Digital signatures”]

In each of the above sections, the following changes MUST be applied:

* Any reference to the _claim_ MUST be replaced with the _partial claim_ as defined in xref:_partial_claim_definition[xrefstyle=full] of this document.
* Any reference to the _claim generator_ MUST be replaced with the _<<_actor,actor>>_ whose _X.509 certificate_ is being used for this assertion.

[NOTE]
.TO DO: Review C2PA spec for additional adaptions that might be relevant.
====
* Is the EKU usage still valid for this purpose?
* Is the trust list the same?
====

==== Validating the COSE signature

NOTE: TO DO: Write this section. Similar to the generation section, I expect it will largely leverage the C2PA spec.

== Trust model

IMPORTANT: This section augments link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_trust_model++[Section 15, “Trust model,”] of the C2PA spec by adding additional trust signals related to the identity of _<<_actor,actors>>_ involved in creation of a _<<C2PA asset>>._ It does not replace any portion of the C2PA trust model.

[NOTE]
.TO DO: Describe the trust signals that are intended to be conveyed by this assertion. Adapt from or possibly reference the following documents:
====
* link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_trust_model++[15. Trust model] in C2PA technical specification
* link:++https://c2pa.org/specifications/specifications/1.0/security/Security_Considerations.html#_trust_model++[2.2 Trust model] in C2PA security considerations
* link:++https://www.w3.org/TR/vc-data-model/#ecosystem-overview++[1.2 Ecosystem Overview] in W3C verifiable credentials spec
* link:++https://www.w3.org/TR/vc-data-model/#use-cases-and-requirements++[1.3 Use Cases and Requirements] in W3C verifiable credentials spec
====

== User experience

_This section is non-normative._

[NOTE]
.TO DO:
====
* Think through wallet-holder experience challenges, especially when batch-producing assets.
* Think through async issues and online failure cases involved in verifying VC/DID document chains.
====

== Open issues / discussion

_This section is non-normative._

Resolve the following topics before producing a 1.0 version of this spec:

* How to express the credential holder’s role in relation to the manifest or specific actions in the manifest? The soon-to-be-deprecated `stds.schema-org.CreativeWork` assertion offered many options.
** Related: Describe how to allow other assertions to refer to _this_ assertion.
* Think through what information needs to be presented to wallet/credential holder so that the wallet can provide a suitable user experience. This likely requires that the asset itself has a credential and a suitable credential schema, which will likely need to incorporate a summary of actions and ingredients. (Can a small thumbnail be included as well?)
* Find a home for following statement, adapted from 1.3 C2PA spec: Since an identity assertion can contain personally identifiable information, there may be workflows where it is necessary to remove/redact an identity assertion. This can be accomplished by following the workflow described in link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_redaction_of_assertions++[Section 6.7, “Redaction of assertions,”] of the C2PA technical specification.
