= Identity Assertion
:toc: macro
:toc-title:
:sectanchors:
:sectnums:
:sectnumlevels: 5

The link:https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html[*C2PA technical specification*] allows _<<_actor,actors>>_ in a workflow to make cryptographically signed _<<_c2pa_assertion,assertions>>_ about the produced _<<C2PA asset>>._ This signature is issued by the vendor whose software or hardware was used to create the _<<_c2pa_assertion,C2PA assertions>>_ and the _<<C2PA claim>>,_ which is why it is called the _<<C2PA claim generator>>._

This specification describes a _<<C2PA assertion>>_ referred to here as the *<<_identity_assertion,identity assertion>>* that can be added to a _<<C2PA Manifest>>_ to enable a _<<_credential_holder,credential holder>>_ to prove control over a digital identity and to use that identity to document the _<<_named_actor,named actor’s>>_ role(s) in the _<<C2PA asset>>’s_ lifecycle.

Version 1.1 (adding identity claims aggregation) *Draft 04 November 2024* · xref:_version_history[]

IMPORTANT: This specification differs from the link:https://creator-assertions.github.io/identity/1.0/[1.0 version] primarily in the addition of xref:_identity_claims_aggregation[xrefstyle=full].

[#maintainers]
*Maintainers:*

* mailto:scouten@adobe.com[Eric Scouten] (https://adobe.com[Adobe])

include::partial$license.adoc[]
include::partial$contributing.adoc[]
include::partial$foreword.adoc[]
include::partial$toc.adoc[]

== Introduction

_This section is non-normative._

=== Scope

This specification describes a _<<C2PA assertion>>_ that allows a _<<_named_actor,named actor>>_ to document their relationship to a _<<C2PA asset>>_ produced by them or on their behalf independently from the _<<C2PA claim generator>>,_ and to allow _<<_identity_assertion_consumer,consumers>>_ of a _<<C2PA asset>>_ to independently verify that the received asset was in fact produced by the _<<_named_actor,named actor>>_ and has not been tampered with.

IMPORTANT: For purposes of the Community Specification License, the link:https://github.com/creator-assertions/identity-assertion/blob/main/scope.md[scope.md document] at the root of this project’s GitHub repository is the governing document of this specification’s scope.

This specification draws upon and extends existing work from two standards organizations:

=== C2PA technical specification

The https://c2pa.org[Coalition for Content Provenance and Authenticity (C2PA)] has developed a link:https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html[technical specification] for providing content provenance and authenticity. It is designed to enable global, opt-in, adoption of digital provenance techniques through the creation of a rich ecosystem of digital provenance enabled applications for a wide range of individuals and organizations while meeting appropriate security requirements.

The C2PA technical specification allows other standards bodies to define additional metadata that can be incorporated into a _<<C2PA Manifest>>._ These statements come in the form of a _<<_c2pa_assertion,C2PA assertion>>._

This specification describes a specific _<<C2PA assertion>>_ that can be added to a _<<C2PA Manifest>>_ to allow an _<<_actor,actor>>_ to prove control over an digital identity and to bind that identity to a _<<_c2pa_asset,C2PA asset>>_ (and, at their option, one or more _<<_c2pa_assertion,C2PA assertions>>_) produced by them or on their behalf.

IMPORTANT: This document references link:https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html[version 2.1 of the C2PA technical specification], but it is compatible with all prior versions of the specification. Where there is a meaningful difference between versions of the C2PA specification, those will be described here.

=== Trust over IP technical architecture

The https://trustoverip.org[Trust over IP Foundation (ToIP)] has developed a https://github.com/trustoverip/TechArch/blob/main/spec.md[technical architecture specification] for describing a decentralized digital trust infrastructure.

NOTE: This specification refers to a “public review draft” of the ToIP technical architecture specification published on 14 November 2022 which is current as of the writing of this specification.

The ToIP architecture specification introduces the concept of _<<_toip_verifiable_identifier,verifiable identifier>>_ as follows:

> Design Principle #5 (https://trustoverip.org/permalink/Design-Principles-for-the-ToIP-Stack-V1.0-2022-11-17.pdf[Cryptographic Verifiability]) states that “messages and data structures exchanged between parties should be verifiable as authentic using standard cryptographic algorithms and protocols”. This requires that Endpoint Systems be able to associate, discover and verify the cryptographic keys associated with a ToIP identifier. This specification will refer to identifiers that meet this basic requirement of cryptographic verifiability as verifiable identifiers (VIDs).
-- https://github.com/trustoverip/TechArch/blob/main/spec.md#64-toip-identifiers[Section 6.4: ToIP identifiers]

NOTE: The ToIP definition of the term “verifiable identifier” is well-aligned with the design goals of this specification. As of this writing, ToIP has just begun the process of producing a technical standard that describes how to _implement_ verifiable identifiers. This specification will incorporate relevant technical standards for verifiable identifiers as they become available.

This specification describes mechanisms to support two common individual and organizational identity mechanisms that fit the conceptual description of _<<ToIP verifiable identifier>>:_

* https://www.w3.org/TR/did-core/[Decentralized identifiers (DIDs)] as defined by W3C
* https://tools.ietf.org/html/rfc5280[X.509 certificates]

=== Conceptual overview

Each *<<_identity_assertion,identity assertion>>* instance allows exactly one _<<_credential_holder,credential holder>>_ to sign a data structure known as `signer_payload`, which among other things includes a list of _<<_c2pa_assertion,C2PA assertions>>_ which will subsequently be included in a _<<C2PA Manifest>>._

The _<<_credential_holder,credential holder’s>>_ signature should generally be construed as reflective of the _<<_named_actor,named actor’s>>_ authorization of or active participation in the production of the the _<<C2PA asset>>_ in which it appears, as described by the specific _<<_c2pa_assertion,C2PA assertions>>_ that are referenced in the *<<_identity_assertion,identity assertion>>.*

Each *<<_identity_assertion,identity assertion>>* contains a `signer_payload` with hashlink references to one or more other _<<_c2pa_assertion,C2PA assertions>>,_ known here as _<<_referenced_assertions,referenced assertions>>,_ and a signature from the _<<_credential_holder,credential holder>>_ over that payload, thus providing a non-repudiable, tamper-evident binding between the _<<_named_actor,named actor>>_ and the list of _<<_referenced_assertions,referenced assertions>>._

The `signer_payload` and corresponding signature from the _<<_credential_holder,credential holder>>_ binds this identity assertion to a specific _<<C2PA asset>>_ and allows the _<<_credential_holder,credential holder>>_ to endorse or make additional statements about the _<<_named_actor,named actor’s>>_ relationship to that _<<C2PA asset>>._

The *<<_identity_assertion,identity assertion>>* should be thought of as a trust signal that is independent from (and thus, in _addition_ to) the trust signal provided by the _<<C2PA claim generator>>_ itself.

[#trust-signal-scope-one-ia]
.Trust signal scope with one identity assertion
[example]
====
The diagram that follows, with one _<<C2PA Manifest>>_ containing one *<<_identity_assertion,identity assertion>>,* is intended to illustrate the most basic example of the two trust signals available and how they intersect:

.Overview of identity assertion
image::overview/single-ia-trust-bubbles.drawio.svg[Single identity assertion trust example,width=240,height=400,align="center"]

In this notation, the small blue circles (A1, A2, etc.) are intended to represent any assertion other than an *<<_identity_assertion,identity assertion>>* or _<<_hard_binding,hard binding>>_ assertion. (As examples, any of these could represent an actions assertion, a metadata assertion, or a thumbnail assertion.) The black circle (HB) is used to represent the _<<_hard_binding,hard binding>>_ assertion, which is a required part of a valid _<<C2PA Manifest>>._ The yellow circle demonstrates the limit of *<<_identity_assertion,identity assertion 1’s>>* trust signal. The teal circle demonstrates the limit of the _<<_c2pa_manifest,C2PA Manifest’s>>_ trust signal.

The following diagram shows *<<_identity_assertion,identity assertion 1>>* using the _<<_credential_holder,credential holder’s>>_ signature to seal:

* assertions A1 and A2,
* the portion of the asset that does not include the _<<C2PA Manifest Store>>_ (via HB), and
* any other information in `signer_payload`.

.Identity assertion structure
image::overview/identity-assertion-structure.drawio.svg[Trust model for identity assertion,width=490,height=430,align="center"]

The following diagram shows the _<<C2PA Manifest>>_ using the _<<_claim_generator,claim generator’s>>_ signature to seal:

* assertions A1, A2, and A3,
* identity assertion 1,
* the portion of the asset that does not include the _<<C2PA Manifest Store>>_ (via HB), and
* any other information in the claim data structure.

.C2PA Manifest structure
image::overview/manifest-structure.drawio.svg[Trust model for C2PA Manifest,width=520,height=470,align="center"]
====

The *<<_identity_assertion,identity assertion>>* may be repeated any number of times to convey information specific to distinct _<<_named-actor,named actors>>._

[#trust-signal-scope-two-ias]
.Trust signal scope with two non-overlapping identity assertions
[example]
====
The diagram that follows extends xref:trust-signal-scope-one-ia[xrefstyle=full], by showing how two *<<_identity_assertion,identity assertions>>* could be used to describe distinct assertions attested to by two distinct _<<_named_actor,named actors>>:_

.Two non-overlapping identity assertions
image::overview/non-overlapping-trust-bubbles.drawio.svg[Two non-overlapping identity assertions example,width=400,height=400,align="center"]

In this example, *<<_identity_assertion,identity assertion 1>>* is using its _<<_credential_holder,credential holder’s>>_ signature to seal:

* assertions A1 and A2,
* the portion of the asset that does not include the _<<C2PA Manifest Store>>_ (via HB), and
* any other information in its `signer_payload`.

The yellow circle demonstrates the limit of *<<_identity_assertion,identity assertion 1’s>>* trust signal.

In this example, *<<_identity_assertion,identity assertion 2>>* is using its _<<_credential_holder,credential holder’s>>_ signature to seal:

* assertions A3, A4, and A5,
* the portion of the asset that does not include the _<<C2PA Manifest Store>>_ (via HB), and
* any other information in its `signer_payload`.

The dark blue circle demonstrates the limit of *<<_identity_assertion,identity assertion 2’s>>* trust signal.

Separately, the _<<C2PA Manifest>>_ uses the _<<_claim_generator,claim generator’s>>_ signature to seal:

* assertions A1, A2, A3, A4, A5, and A6,
* identity assertion 1,
* identity assertion 2,
* the portion of the asset that does not include the _<<C2PA Manifest Store>>_ (via HB), and
* any other information in the claim data structure.

The teal circle demonstrates the limit of the _<<_c2pa_manifest,C2PA Manifest’s>>_ trust signal.
====

An *<<_identity_assertion,identity assertion>>* may reference one or more other *<<_identity_assertion,identity assertions>>.* As an example, this might be used to convey an organizational endorsement of an individual creator’s credential.

[#trust-signal-scope-nested-ias]
.Trust signal scope with nested identity assertions
[example]
====
The diagram that follows modifies xref:trust-signal-scope-two-ias[xrefstyle=full], by showing how one *<<_identity_assertion,identity assertion>>* could be used to attest to the validity of another *<<_identity_assertion,identity assertion>>:*

.Nested identity assertions
image::overview/nested-trust-bubbles.drawio.svg[Nested identity assertions example,width=400,height=400,align="center"]

In this example, *<<_identity_assertion,identity assertion 1>>* is using its _<<_credential_holder,credential holder’s>>_ signature to seal:

* assertions A1 and A2,
* the portion of the asset that does not include the _<<C2PA Manifest Store>>_ (via HB), and
* any other information in its `signer_payload`.

The yellow circle demonstrates the limit of *<<_identity_assertion,identity assertion 1’s>>* trust signal.

In this example, *<<_identity_assertion,identity assertion 2>>* is using its _<<_credential_holder,credential holder’s>>_ signature to seal:

* assertions A1, A2, A3, A4, and A5,
* identity assertion 1,
* the portion of the asset that does not include the _<<C2PA Manifest Store>>_ (via HB), and
* any other information in its `signer_payload`.

The dark blue circle demonstrates the limit of *<<_identity_assertion,identity assertion 2’s>>* trust signal, which completely overlaps the limit of *<<_identity_assertion,identity assertion 1’s>>* trust signal.

Separately, the _<<C2PA Manifest>>_ uses the _<<_claim_generator,claim generator’s>>_ signature to seal:

* assertions A1, A2, A3, A4, A5, and A6,
* identity assertion 1,
* identity assertion 2,
* the portion of the asset that does not include the _<<C2PA Manifest Store>>_ (via HB), and
* any other information in the claim data structure.

The teal circle demonstrates the limit of the _<<_c2pa_manifest,C2PA Manifest’s>>_ trust signal.
====

=== Use cases and examples

The following is a non-exhaustive list of potential and general use cases for the *<<_identity_assertion,identity assertion>>.* Some of these are taken from, or built upon, the use cases developed within the link:https://www.originproject.info/[Project Origin Alliance] and the link:https://contentauthenticity.org/[Content Authenticity Initiative (CAI)] frameworks. Each use case will be described using some generic personas to help make the flow clear.

IMPORTANT: The identity assertion SHOULD NOT be construed to convey _ownership_ of a _<<C2PA asset>>._ Ownership and rights transfers often take place outside of the digital realm. It is outside the scope of this specification to describe such transfers. It is possible that some other assertion could convey such information; such an assertion could be included in the set of _<<_referenced_assertions,referenced assertions.>>_

==== Enhancing clarity around provenance and edits for journalistic work

A photojournalist Alice uses a Content Credentials-enabled capture device during a newsworthy event she is covering. Her capture device is linked to a digital wallet containing her professional credentials and records her identity in each captured asset. She then imports these assets into a Content Credentials-enabled editing application. Her identity is again associated with the edits that she has made. After editing, she sends her assets to her photo editor, Bob. Bob makes additional edits also using a Content Credentials-enabled application. A new identity assertion is recorded for these edits identifying Bob as the person responsible for those edits. The finalized asset is moved into the content management system of a news organization, which is also Content Credentials-enabled, before posting the asset to social media. Anyone viewing these assets can see the identity of Alice, Bob, and the news organization in a Content Credentials-enabled viewer.

==== Enhance the evidentiary value of critical footage

A human rights defender Jane manages to capture footage containing Content Credentials-enabled provenance of violence during a protest. Jane’s capture device is linked to a digital wallet containing her professional credentials and records her identity in each captured asset. Jane sends the footage to a human rights organization that verifies that the asset meets video-as-evidence criteria. The human rights organization determines that releasing Jane’s identity to the public could pose a safety or privacy risk, so they redact the identity assertion using a Content Credentials-enabled editing application before publishing the footage.

==== Election integrity and protecting political campaigns from deepfakes

Aarav is the director of social communications for a political candidate in an upcoming election. He feels concerned that in efforts to manipulate voters, bad actors will create deepfake videos to misrepresent the candidate. To protect the campaign, Aarav decides that all official communications will be created, produced, and published with Content Credentials-enabled tools. The identity assertion equips Aarav and his team with the ability to represent the campaign as the organizational author of the content that they publish. Aarav encourages voters to verify any digital campaign content to ensure that the material has Content Credentials that link the assets to the campaign.

==== Brand protection in digital marketing

An advertising agency representing a popular sneaker brand wants to ensure that consumers are only purchasing the shoes through official channels. They have found several fraudulent campaigns online claiming to offer the shoes at a discount. To address these scams, the agency decides to incorporate Content Credentials into their creative process, using the identity assertion to represent the designer responsible for the campaign. Before the campaign goes live, the agency redacts the designer’s name and publishes the assets with Content Credentials using the identity assertion to represent the sneaker brand. Now consumers can refer to Content Credentials to identify legitimate promotional campaigns from the sneaker brand.

==== Attribution for digital creators

One morning, Charlie, an up-and-coming digital artist, woke up to find that one of their designs went viral on social media. Charlie felt upset to see their art detached from their name. Charlie had spent months working on their artwork and was disappointed not to receive credit or compensation for their work. Moving forward, Charlie decides to use the identity assertion to link their name, social media, and copyright information to the art they create. Now, when Charlie posts their content to social media platforms that display Content Credentials, viewers can easily link the artwork back to Charlie.

==== Audio sampling and artistic collaboration

Eve is a musician with a talent for releasing songs featuring clever lyrics and catchy beats. Ever since Eve’s music gained traction on audio streaming apps, artists have reached out asking permission to sample her beats. Eve views these collaborations as an opportunity to help new listeners discover her music, so it is important to her that the samples are traceable back to her. She decides to begin recording her songs using a Content Credentials-enabled device linked to a digital wallet containing her identity credentials and her profile on music streaming applications. Now, when other artists release songs that sample Eve’s tunes, she can demonstrate her contribution to the final work.

== Normative references

* https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html[C2PA technical specification, version 2.1]
* https://www.w3.org/TR/vc-data-model-2.0/[Verifiable Credentials Data Model, version 2.0]
* https://www.w3.org/TR/did-core/[W3C decentralized identifiers (DIDs), version 1.0]
* https://tools.ietf.org/html/rfc5280[Internet X.509 public key infrastructure certificate] (RFC 5280)

== Terms and definitions

=== Concepts adapted from C2PA technical specification

The following definitions are adapted from the link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_glossary++[glossary] provided in the C2PA technical specification. This specification uses the prefix “C2PA” to denote data structures incorporated from that specification.

==== Actor

A human or non-human (hardware or software) that is participating in the C2PA ecosystem. For example: a camera (capture device), image editing software, cloud service, or the person using such tools.

NOTE: An organization or group of _actors_ may also be considered an _actor_ in the C2PA ecosystem.

==== C2PA asset

A file or stream of data containing _digital content,_ _asset metadata,_ and a <<C2PA Manifest>>.

For the purposes of this definition, we will extend the typical definition of “file” to include cloud-native and dynamically-generated data.

IMPORTANT: The definition of “C2PA asset” in this specification differs from the definition of “asset” given in the C2PA technical specification. A “C2PA asset” as defined in _this_ specification MUST contain a <<C2PA Manifest>>.

==== C2PA claim

A digitally signed and tamper-evident data structure that references a set of _<<_c2pa_assertion,assertions>>_ by one or more _<<_actor,actors>>,_ concerning a _<<C2PA asset>>,_ and the information necessary to represent the _<<_content_binding,content binding>>._ If any _<<_c2pa_assertion,C2PA assertions>>_ were redacted, then a declaration to that effect is included. This data is a part of the _<<C2PA Manifest>>._

See link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_claims++[Section 10, “Claims,”] of the C2PA technical specification.

==== C2PA claim generator

The non-human (hardware or software) _<<_actor,actor>>_ that generates the _<<C2PA claim>>_ about a _<<C2PA asset>>_ as well as the claim signature, thus leading to the _<<C2PA asset>>'s_ associated _<<C2PA Manifest>>._

==== C2PA assertion

A data structure which represents a statement asserted by an _<<_actor,actor>>_ concerning the _<<C2PA asset>>._ This data is a part of the _<<C2PA Manifest>>._

See link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_assertions++[Section 6, “Assertions,”] of the C2PA technical specification.

==== C2PA Manifest

The set of information about the _provenance_ of a _<<C2PA asset>>_ based on the combination of one or more _<<_c2pa_assertion,C2PA assertions>>_ (including _<<_content_binding,content bindings>>_), a single _<<C2PA claim>>,_ and a _claim signature._ A _C2PA Manifest_ is part of a _C2PA Manifest Store._

NOTE: A _C2PA Manifest_ can reference other _C2PA Manifests._

See link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_manifests++[Section 11, “Manifests,”] of the C2PA technical specification.

==== C2PA Manifest Consumer

An _<<_actor,actor>>_ who consumes a _<<_c2pa_asset,C2PA asset>>_ with an associated _<<C2PA Manifest>>_ for the purpose of obtaining the provenance data from the _<<C2PA Manifest>>._

==== C2PA Manifest Store

A collection of _<<_c2pa_manifest,C2PA Manifests>>,_ which collectively describe the provenance history of a single _<<C2PA asset>>._

See link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_manifest_store++[Section 11.1.4.2, “Manifest Store,”] of the C2PA technical specification.

==== Content binding

Information that associates digital content to a specific _<<C2PA Manifest>>_ associated with a specific _<<C2PA asset>>,_ either as a _hard binding_ or a _soft binding._

Content bindings are described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_binding_to_content++[Section 9, “Binding to content,”] of the C2PA technical specification.

==== Hard binding

One or more cryptographic hashes that uniquely identifies either the entire _<<C2PA asset>>_ or a portion thereof.

Hard bindings are described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hard_bindings++[Section 9.2, “Hard bindings,”] of the C2PA technical specification.

=== Concepts adapted from W3C verifiable credentials specification

The following definitions are adapted from the link:++https://www.w3.org/TR/vc-data-model-2.0/#terminology++[W3C verifiable credentials data model] specification, version 2.0. This specification uses the prefix “W3C” to denote concepts incorporated from that specification.

==== W3C verifiable credential

A tamper-evident credential that has authorship that can be cryptographically verified.

==== W3C decentralized identifier

A portable URL-based identifier, also known as a *DID,* associated with an entity. These identifiers are most often used in a _<<W3C verifiable credential>>_ and are associated with _<<_credential_subject,credential subjects>>_ such that a _<<W3C verifiable credential>>_ itself can be easily ported from one repository to another without the need to reissue the _<<W3C verifiable credential>>_. An example of a DID is `did:example:123456abcdef`.

==== W3C decentralized identifier document

Also referred to as a *DID document,* this is a document that is accessible using a verifiable data registry and contains information related to a specific _<<W3C decentralized identifier>>,_ such as the associated repository and public key information.

=== Other concepts

==== Credential holder

The _<<_actor,actor>>_ that has control (specifically signature authority) over a _<<ToIP verifiable identifier>>_ that describes a specific _<<_named_actor,named actor>>._

==== Credential revocation

An action signifying that a digital credential can no longer be considered as valid. This is typically indicated by an action on the part of the credential issuer stating that they can no longer attest to the validity of the information in the credential or an action on the part of the _<<_credential_holder,credential holder>>_ stating that the public/private key pair associated with the credential is no longer valid.

Adapted from link:++https://trustoverip.github.io/ctwg-main-glossary/#term:revocation++[Trust Over IP’s definition of revocation].

==== Identity claims aggregator

An _<<_actor,actor>>_ that collects identity claims (attestations) regarding a _<<_named actor,named actor>>_ from various _<<_identity_provider,identity providers>>_ and can replay those identity claims into *<<_identity assertion,identity assertions>>* on behalf of the _<<_named_actor,named actor>>._ This _<<_actor,actor>>_ MAY be the same as the _<<_identity_assertion_generator,identity assertion generator>>._

==== Identity assertion

A _<<C2PA assertion>>_ that allows a _<<_credential_holder,credential holder>>_ to prove control over an digital identity and bind the identity to a set of _<<_c2pa_assertion,C2PA assertions>>_ produced by them or on their behalf.

==== Identity assertion consumer

A _<<C2PA Manifest Consumer>>_ who also consumes and interprets the content of any *<<_identity_assertion,identity assertions>>* contained within the _<<C2PA Manifest>>._

NOTE: This role can also be thought of as a *relying party* or *verifier* as defined in specifications such as the link:++https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifier++[W3C verifiable credentials data model].

==== Identity assertion generator

The non-human (hardware or software) _<<_actor,actor>>_ that is responsible for generating the *<<_identity_assertion,identity assertion>>.* This MAY be the same _<<_actor,actor>>_ as the _<<C2PA claim generator>>._

==== Identity provider

An _<<_actor,actor>>_ that is attesting to an identity of the _<<_named_actor,named actor>>_ as understood in the context of the _identity provider._ This _<<actor,actor>>_ MAY be the _<<identity_assertion_generator,identity assertion generator>>,_ a third party contacted by the _<<identity_assertion_generator,identity assertion generator>>,_ or the issuer of an identity credential that is used by the _<<identity_assertion_generator,identity assertion generator>>._

==== Named actor

The _<<_actor,actor>>_ whose relationship to a _<<C2PA asset>>_ is documented by an *<<_identity_assertion,identity assertion>>.* This may also be referred to as a _credential subject_ when identified by the *subject* field of a _<<ToIP verifiable identifier>>._

IMPORTANT: A _named actor_ may be any form of _<<_actor,actor>>,_ including an individual human, an organization of humans, or a non-human (software or hardware device).

IMPORTANT: The _named actor_ is not necessarily the same _<<_actor,actor>>_ as the _<<_credential_holder,credential holder>>,_ though there is an implied trust relationship between the two _<<_actor,actors>>._

==== Natural language string

A sequence of UTF-8 characters that is intended to be displayed to a human user. When contained within a JSON or CBOR data structure, this may be either:

* a single string object, in which case this string is to be displayed as-is to users, regardless of their expressed language preference, or
* a JSON or CBOR map, in which case the contents should be interpreted as described in link:https://www.w3.org/TR/vc-data-model-2.0/#language-and-base-direction[§11.1, “Language and base direction,”] of the W3C verifiable credential data model specification.

The string MUST resolve to a non-empty sequence of UTF-8 characters for all supported languages.

==== Placeholder assertion

A temporary _<<C2PA assertion>>_ that is created during _<<C2PA claim>>_ generation which reserves space for the eventual content of the *<<_identity_assertion,identity assertion>>.* A placeholder assertion MUST be used when the final file layout of the _<<C2PA asset>>_ is required for the _<<_hard_binding,hard binding>>_ assertion, as described in xref:_interaction_with_data_hash_assertion[xrefstyle=full].

==== Referenced assertions

The set of _<<_c2pa_assertion,C2PA assertions>>_ that are referenced by an *<<_identity_assertion,identity assertion>>* and thus bound to (i.e. authorized by or created by) the _<<_credential_holder,credential holder>>_ named in the *<<_identity_assertion,identity assertion>>.*

==== ToIP verifiable identifier

Any identifier for which an endpoint system is “able to associate, discover and verify the cryptographic keys associated with a ToIP identifier.” This satisfies the ToIP design principle that “messages and data structures exchanged between parties should be verifiable as authentic using standard cryptographic algorithms and protocols.”

See link:++https://github.com/trustoverip/TechArch/blob/v1-PR1/spec.md#64-toip-identifiers++[ToIP identifiers] in the ToIP technology architecture specification.

==== Trust

In the context of an *<<_identity_assertion,identity assertion>>,* we define _trust_ as meeting or exceeding the minimum level of confidence an _<<_identity_assertion_consumer,identity assertion consumer>>_ requires over assertions made about the identity of the _<<_named_actor,named actor>>_ and the _<<_named_actor,named actor’s>>_ true intention regarding their attestations via content included in and referenced by the *<<_identity_assertion,identity assertion>>.*

==== Trust list

A list of _<<_actor,actors>>,_ published by an authoritative source that are trusted in a specific context.

Adapted from link:++https://trustoverip.github.io/ctwg-main-glossary/#term:trust-list++[Trust Over IP’s definition of trust list].

A _trust list_ can be considered a simplified form of a link:++https://trustoverip.github.io/ctwg-main-glossary/#term:trust-registry++[trust registry].

include::partial$terms.adoc[]

== Assertion definition

=== Overview

This specification defines a _<<C2PA assertion>>_ known as an *<<_identity_assertion,identity assertion>>* which MAY be used to bind one _<<_named_actor,named actor>>_ to a set of _<<_referenced_assertions,referenced assertions>>_ and other related data, known overall as the _signer payload._ This binding SHOULD generally be construed as authorization of or participation in the creation of the statements described by those assertions and corresponding portions of the _<<C2PA asset>>_ in which they appear.

The *<<_identity_assertion,identity assertion>>* contains the following data fields:

* `signer_payload` contains the set of data to be signed by this _<<_credential_holder,credential holder>>_.
* `signature` contains the raw byte stream of the _<<_credential_holder,credential holder>>’s_ signature
* `pad1` and `pad2` are byte strings filled with binary `0x00` values used to fill space

The `signer_payload` field is a structure of type `signer-payload-map` which is signed by the _<<_credential_holder,credential holder>>_. It contains the following fields:

* `referenced_assertions` _(required)_ is an array of `hashed-uri-map` structures with one entry for every _<<_referenced_assertions,referenced assertion>>_ chosen by the _<<_credential_holder,credential holder>>._ It is subject to several requirements as described in xref:_referenced_assertions_requirements[xrefstyle=full].
* `sig_type` _(required)_ is a string identifying the data type of the signature. Valid credential types and the corresponding `signature` data structures and `signer_payload.sig_type` values are defined in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].
* `role` _(optional)_ contains one or more descriptions of the _<<_named_actor,named actor’s>>_ relationship(s) to the _<<C2PA asset>>._ Possible role values are described in xref:_named_actor_roles[xrefstyle=full].
* `expected_partial_claim` _(optional),_ if present, describes the content of the expected _<<C2PA claim>>,_ in which the *<<_identity_assertion,identity assertion>>* appears. It can be used to prevent the introduction or removal of _<<_c2pa_assertion,C2PA assertions>>_ (other than the _<<_referenced_assertion,referenced assertions>>_) that could create unintended or unexpected semantics for the overall _<<C2PA Manifest>>._ The method for calculating this field is described in xref:_calculating_the_expected_partial_claim_field[xrefstyle=full].
* `expected_claim_generator` _(optional),_ if present, describes the X.509 certificate of the expected _<<C2PA claim generator>>._ It can be used to avoid creating an unwanted association between the _<<_named_actor,named actor>>_ and an unexpected or undesired _<<C2PA claim generator>>._ The method for calculating this field is described in xref:_calculating_the_expected_claim_generator_field[xrefstyle=full].
* `expected_countersigners` _(optional),_ if present, describes the content of other *<<_identity_assertion,identity assertion>>* in the same _<<C2PA Manifest>>._ The method for calculating this field is described in xref:_calculating_the_expected_countersigners_field[xrefstyle=full].

The *<<_identity_assertion,identity assertion>>* SHALL have a label of `cawg.identity`.

Multiple identity assertions may be used in the same _<<C2PA Manifest>>_ to describe the distinct roles of multiple _<<_actor,actors>>_ in creating a single _<<C2PA asset>>._ This is illustrated in the xref:multiple-identity-assertions[multi-author example] from the conceptual overview. If this occurs, these assertions SHALL be given unique labels as described by link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_multiple_instances++[Section 6.4, “Multiple instances,”] of the C2PA technical specification.

==== Referenced assertions requirements

The list of _<<_referenced_assertions,referenced assertions>>_ contained in `signer_payload.referenced_assertions` is subject to the following requirements:

* For each assertion listed, an assertion with the same `url`, `alg`, and `hash` values MUST also be listed in the `created_assertions`, `generated_assertions`, or `assertions` field of the _<<C2PA claim>>_ in which the *<<_identity_assertion,identity assertion>>* appears.

NOTE: The `assertions` field appears only in version 1.x of the C2PA technical specification. It was replaced with `created_assertions` and `generated_assertions` in version 2.0 of the C2PA technical specification.

* The list MUST NOT reference any assertion more than once.
* The list MUST include a _<<_hard_binding,hard binding>>_ assertion as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hard_bindings++[Section 9.2, “Hard bindings,”] of the C2PA technical specification.
* The list MAY reference other *<<_identity_assertion,identity assertions>>,* provided that no cycle of references among *<<_identity_assertion,identity assertions>>* is created.

NOTE: The requirement that the `hash` value for a _<<_referenced_assertions,referenced assertion>>_ be known prior to presenting `signer_payload` for signature implies that an *<<_identity_assertion,identity assertion>>* MUST NOT refer to itself.

==== Named actor roles

The _<<_credential_holder,credential holder>>_ MAY choose to describe one or more relationships of the _<<_named_actor,named actor>>_ to the _<<C2PA asset>>_ by adding a `role` field to `signer_payload`.

If present, the value for `role` MUST be a non-empty CBOR array of non-empty text strings. It is recommended that the CBOR text strings be chosen from the following values and that any user experience that presents the content of an *<<_identity_assertion,identity assertion>>* be prepared to describe these roles in the same human language as the surrounding interface:

[width="100%",cols="4,10",options="header"]
|=======================
| Value        |  Meaning
| `cawg.creator` | The _<<_named_actor,named actor>>_ is a primary creator/author of this _<<C2PA asset>>._
| `cawg.contributor` | The _<<_named_actor,named actor>>_ is a secondary creator/author of this _<<C2PA asset>>._
| `cawg.editor` | The _<<_named_actor,named actor>>_ is an editor of this _<<C2PA asset>>._
| `cawg.producer` | The _<<_named_actor,named actor>>_ is a producer of this _<<C2PA asset>>._
| `cawg.publisher` | The _<<_named_actor,named actor>>_ is a publisher of this _<<C2PA asset>>._
| `cawg.sponsor` | The _<<_named_actor,named actor>>_ has supported or sponsored the creation of this _<<C2PA asset>>._
| `cawg.translator` | The _<<_named_actor,named actor>>_ has adapted of this _<<C2PA asset>>_ from a similar work in another language.
|=======================

Other CBOR text string values MAY be used for `role`, subject to the restrictions described in xref:_labels[xrefstyle=full].

=== CBOR schema

The schema for this type is defined by the `identity` rule in the following https://datatracker.ietf.org/doc/html/rfc8610[CDDL definition]:

[source,cddl]
----
identity = {
  "signer_payload": $signer-payload-map, ; content to be signed by credential holder
  "signature": bstr, ; byte string of the signature
  "pad1": bstr, ; byte string filled with binary `0x00` values used for filling up space
  ? "pad2": bstr, ; optional byte string filled with binary `0x00` values used for filling up space
}

signer-payload-map = {
  "referenced_assertions": [1* $hashed-uri-map],
  "sig_type": tstr .size (1..max-tstr-length), ; a string identifying the data type of the signature field
  ? "role": [1* tstr .size (1..max-tstr-length)], ; one or more strings defining the named actor’s relationship(s) to this C2PA asset
  ? "expected_partial_claim": $hash-map, ; hash of expected partial claim
  ? "expected_claim_generator": $hash-map, ; hash of expected claim signer credential
  ? "expected_countersigners": [1* $expected-countersigner-map], ; array of expected other identity assertion descriptions
}

hash-map = {
  "alg": tstr .size (1..max-tstr-length), ; a string identifying the cryptographic hash algorithm used to compute this hash, taken from the C2PA hash algorithm identifier list
  "hash": bstr, ;  byte string containing the hash value
}

expected-countersigner-map = {
  "partial_signer_payload": $signer-payload-map ; signer_payload map from other identity assertion minus any `expected_countersigner` field
  ? "expected_credentials": $hash-map ; expected identity assertion credentials
}
----

IMPORTANT: Future minor version updates (1.1, 1.2, etc.) to this specification MAY add new fields to the `signer-payload-map` description, provided that such new data members are optional and there is a well-specified default meaning that is compatible with the 1.0 version of this specification. Such updates to the specification SHOULD continue to use the `cawg.identity` assertion label.

Possible values for the `signer_payload.sig_type` field and the corresponding interpretations of the `signature` field are described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

The `hashed-uri-map` rule is defined in link:++https://c2pa.org/specifications/specifications/1.3/specs/C2PA_Specification.html#_hashed_uris++[Section 8.3.1, “Hashed URIs,”] of the C2PA technical specification.

Possible values for the text string entries in the `signer_payload.role` field are provided in xref:_named_actor_roles[xrefstyle=full].

==== Example

An example in https://www.rfc-editor.org/rfc/rfc8949.html#name-diagnostic-notation[CBOR-Diag] is shown below, which is non-normative:

[source,json]
----
{
  "signer_payload": {
    "sig_type": "cawg.x509.cose",
    "referenced_assertions": [
      {
        "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.hash.data",
        "hash": b64'U9Gyz05tmpftkoEYP6XYNsMnUbnS/KcktAg2vv7n1n8='
      },
      {
        "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.thumbnail.claim.jpeg",
        "hash": b64'G5hfJwYeWTlflxOhmfCO9xDAK52aKQ+YbKNhRZeq92c='
      },
      {
        "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.ingredient.v2",
        "hash": b64'Yzag4o5jO4xPyfANVtw7ETlbFSWZNfeM78qbSi8Abkk='
      }
    ],
    "role": ["cawg.creator"],
  },
  "signature": b64'....', // COSE signature
  "pad1": b64'....', // zero-filled pad buffer
  "pad2": b64'....'  // zero-filled pad buffer
}
----

=== Labels

Several data types in this specification have labels that can be defined either in this specification or by an external entity.

Labels are non-empty string values organized into namespaces using a period (`.`) as a separator. The namespace component of the label can be an entity or a reference to a well-established standard. (See ABNF below.)

Labels defined by the CAWG will begin with `cawg.`. All labels beginning with `cawg.` that are not defined in the current version of the specification are reserved for the future use of the CAWG and MUST NOT be assigned by any other entity. Future minor version updates (1.2, 1.3, etc.) to this specification MAY define new values for any label using the `cawg.` prefix.

Entity-specific labels (i.e. those not defined by CAWG) SHALL begin with the Internet domain name for the entity similar to how Java packages are defined (e.g., `com.litware`, `net.fineartschool`). 

[[abnf_for_labels]]
[source,abnf]
.ABNF for labels
----
namespaced-label = qualified-namespace label
qualified-namespace = "cawg" / entity
entity = entity-component *( "." entity-component )
entity-component = 1( DIGIT / ALPHA ) *( DIGIT / ALPHA / "-" / "_" )
label = 1*( "." label-component )
label-component = 1( DIGIT / ALPHA ) *( DIGIT / ALPHA / "-" / "_" )
----

The period-separated components of a label follow the variable naming convention (`[a-zA-Z][a-zA-Z0-9_-]*`) specified in the POSIX or C locale, with the restriction that the use of a repeated underscore character (`__`) is reserved for labelling multiple assertions of the same type.

WARNING: While the use of labels defined by external entities is permitted, implementers should be aware that such labels may not be widely understood by other implementations.

== Creating the identity assertion

=== Presenting the `signer_payload` data structure for signature

Prior to presenting the _<<_credential_holder,credential holder>>_ with the `signer_payload` data structure for signature, the _<<_referenced_assertions,referenced assertions>>_ MUST themselves be created. This process is described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_creating_assertions++[Section 10.3.1, “Creating assertions,”] of the C2PA technical specification.

The list of _<<_referenced_assertions,referenced assertions>>_ MUST include the same _<<_hard_binding,hard binding>>_ assertion that is present in the _<<C2PA claim>>_ itself. The list of _<<_referenced_assertions,referenced assertions>>_ SHOULD include any _<<_c2pa_assertion,assertions>>_ necessary to allow the _<<_actor,actor>>_ to accurately describe their relationship to the content. For example, a `c2pa.actions` assertion could be referenced to attest that the _<<_actor,actor>>_ performed those specific actions.

The `signer_payload` data structure MUST be presented to be signed by the _<<_credential_holder,credential holder>>_ corresponding to each *<<_identity_assertion,identity assertion>>.* This process is described in more detail in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

IMPORTANT: If a data hash assertion is being used, the _<<_identity_assertion_generator,identity assertion generator>>_ MUST also follow the process described in xref:_interaction_with_data_hash_assertion[xrefstyle=full].

==== Calculating the `expected_partial_claim` field

If the _<<_identity_assertion_generator,identity assertion generator>>_ chooses to include the `expected_partial_claim` field in `signer_payload`, it MUST be computed as follows:

. Create a valid _<<C2PA claim>>_ data structure that includes references to all _<<_c2pa_assertion,C2PA assertions>>,_ *including* all *<<_identity_assertion,identity assertions>>.* The `hash` value for all assertion references MUST be valid and correct, except in the following cases:
.. For the specific *<<_identity_assertion,identity assertion>>* being computed, replace the `hash` value with all zero-value (`0x00`) bytes.
.. For any *<<_identity_assertion,identity assertions>>* whose signing credentials are described via the `expected_countersigners` field, replace the `hash` value with all zero-value (`0x00`) bytes.
. Serialize the _<<C2PA claim>>_ data structure using link:++https://www.rfc-editor.org/rfc/rfc8949.html#name-core-deterministic-encoding++[Section 4.2.1, “Core deterministic encoding,”] of RFC 8949: Concise binary object representation.
. Compute a hash of the serialized _<<C2PA claim>>_ data structure using one of the algorithms documented in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hashing++[Section 13.1, “Hashing,”] of the C2PA technical specification.

The `expected_partial_claim` field SHOULD contain a CBOR map with the following fields:

* `alg` describing the hash algorithm as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hashing++[Section 13.1, “Hashing,”] of the C2PA technical specification, and
* `hash` value containing the computed hash of the serialized _<<C2PA claim>>_ data structure.

==== Calculating the `expected_claim_generator` field

If the _<<_identity_assertion_generator,identity assertion generator>>_ chooses to include the `expected_claim_generator` field in `signer_payload`, it MUST be computed as follows:

. Identify the end-entity signing certificate that will be used for the expected _<<C2PA claim generator>>._
. Serialize this signing certificate as a CBOR byte string as described in link:https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#x509_certificates[Section 14.6, “X.509 certificates,”] of the C2PA technical specification. This serialization should be performed using link:++https://www.rfc-editor.org/rfc/rfc8949.html#name-core-deterministic-encoding++[Section 4.2.1, “Core deterministic encoding,”] of RFC 8949: Concise binary object representation.
. Compute a hash of the serialized end-entity certificate using one of the algorithms documented in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hashing++[Section 13.1, “Hashing,”] of the C2PA technical specification.

The resulting hash should be used as the `expected_claim_generator` field.

The `expected_claim_generator` field SHOULD contain a CBOR map with the following fields:

* `alg` describing the hash algorithm as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hashing++[Section 13.1, “Hashing,”] of the C2PA technical specification, and
* `hash` value containing the computed hash of the serialized certificate.

==== Calculating the `expected_countersigners` field

If the _<<_identity_assertion_generator,identity assertion generator>>_ chooses to include the `expected_countersigners` field in `signer_payload`, it MUST be computed as follows:

. For every _other_ *<<_identity_assertion,identity assertion>>* that will be present in the _<<C2PA Manifest>>:_
.. Calculate the `signer_payload` map for that *<<_identity_assertion,identity assertion>>.* Exclude any `expected_countersigners` field from that `signer_payload` map and place the resulting `signer_payload` structure in the `partial_signer_payload` field of _this_ *<<_identity_assertion,identity assertion’s>>* `expected_countersigners` map.
.. _(optional)_ Identify the signing credential that will be used to sign that *<<_identity_assertion,identity assertion>>.*
... Serialize the signing credential as a CBOR byte string as described in xref:_serialization_for_credential_types[]. This serialization should be performed using link:++https://www.rfc-editor.org/rfc/rfc8949.html#name-core-deterministic-encoding++[Section 4.2.1, “Core deterministic encoding,”] of RFC 8949: Concise binary object representation.
... Compute a hash of the serialized signing credential using one of the algorithms documented in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hashing++[Section 13.1, “Hashing,”] of the C2PA technical specification.
. Once the above materials have been gathered, the `expected_countersigners` field SHOULD contain a CBOR array of CBOR maps, each containing the following fields for each *<<_identity_assertion,identity assertion>>*:
.. `partial_signer_payload` _(required)_ containing the expected `signer_payload`, omitting any `expected_countersigners` field.
.. `expected_credentials` _(optional)_ containing a description of the expected signing credentials:
... `alg` describing the hash algorithm as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hashing++[Section 13.1, “Hashing,”] of the C2PA technical specification, and
... `hash` value containing the computed hash of the serialized signing credential.

==== Serialization for credential types

The signing credential for other *<<_identity_assertion,identity assertions>>* should be serialized depending on the credential type:

[width="100%",cols="4,10",options="header"]
|=======================
| Credential type | Serialization
| X.509 certificate | End-entity certificate
|=======================

=== Creating the assertion

Once the signature is obtained, the *<<_identity_assertion,identity assertion>>* can be created and added to the C2PA Manifest's assertion store, and then referenced in the _<<C2PA claim>>._ If a _<<_placeholder_assertion,placeholder assertion>>_ was previously added to the _<<_c2pa_claim,C2PA claim,>>_ its content MUST now be replaced with the final assertion content as described below.

The `signer_payload` data structure MUST be unchanged from the data structure that was presented to the _<<_credential_holder,credential holder>>_ for signature.

The values for the `signer_payload.sig_type` and `signature` fields depend on the nature of credential used. Some common signature types are described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

The _<<_identity_assertion_generator,identity assertion generator>>_ SHOULD independently validate the signature from the _<<_credential_holder,credential holder>>_ before proceeding.

If a _<<placeholder_assertion,placeholder assertion>>_ was used, the values of the `pad1` and `pad2` fields MUST now be recomputed (adjusted in size) such that the resulting *<<_identity_assertion,identity assertion>>* exactly matches the size in bytes of the _<<placeholder_assertion,placeholder assertion.>>_ If the signature exceeds the space available in the _<<placeholder_assertion,placeholder assertion,>>_ the claim generation process as described in xref:_interaction_with_data_hash_assertion[xrefstyle=full] MUST be repeated with a larger _<<_placeholder_assertion,placeholder assertion>>._

NOTE: Preferred/deterministic CBOR serialization of byte arrays uses a variable-length integer to specify the length of the encoded binary data. When the length goes from zero to one byte, or one to two bytes (etc.), the length of the resulting pad jumps by two bytes. This means that not all paddings can be expressed using a single padding field. For example, 24-byte and 26-byte pads can be created, but a 25-byte pad cannot. If this situation arises, the desired padding can be split between `pad1` and `pad2`. For example, to make a 25-byte pad, an implementation can encode 19 bytes into `pad1` (resulting in an encoded length of 20 bytes), and 4 bytes into `pad2` (resulting in 5 bytes.)

If no _<<placeholder_assertion,placeholder assertion>>_ was used, the values of the `pad1` and `pad2` fields MAY be empty.

The `pad1` and `pad2` fields of an *<<_identity_assertion,identity assertion>>* MUST contain only zero-value (`0x00`) bytes.

=== Interaction with data hash assertion

IMPORTANT: The process described in this section MUST be followed when using a data hash assertion as described by link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_data_hash++[Section 18.5, “Data hash,”] of the C2PA technical specification. This process MAY be followed when using other _<<_hard_binding,hard binding>>_ assertions.

The C2PA technical specification explains the need for pre-computing the _<<_c2pa_asset,C2PA asset’s>>_ final file layout when using a data hash assertion as follows:

> Some asset file formats require file offsets of the C2PA Manifest Store and asset content to be fixed before the manifest is signed, so that _<<_hard_binding,hard bindings>>_ will correctly align with the content they authenticate. Unfortunately, the size of a manifest and its signature cannot be precisely known until after signing, which could cause file offsets to change. For example, in JPEG-1 files, the entire C2PA Manifest Store must appear in the file before the image data, and so its size will affect the file offsets of content being authenticated.
-- link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_multiple_step_processing++[Section 10.4: “Multiple step processing”]

Similarly, the size of the *<<_identity_assertion,identity assertion>>* cannot be known until its signature is obtained. Changing the size of the *<<_identity_assertion,identity assertion>>* after file layout is completed would invalidate the file offsets contained within the data hash assertion.

In this case, it is necessary to use a _<<_placeholder_assertion,placeholder assertion>>_ to reserve space for the content of the final *<<_identity_assertion,identity assertion>>* (including its signature) which will be created later.

When using a data hash assertion, an _<<_identity_assertion_generator,identity assertion generator>>_ MUST follow the process described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_creating_a_claim++[Section 10.3, “Creating a claim,”] and link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_multiple_step_processing++[Section 10.4, “Multiple step processing,”] of the C2PA technical specification with additional steps as described below:

1. link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_creating_assertions++[Section 10.3.1, “Creating assertions.”] Any *<<_identity_assertion,identity assertion>>* that will be added to the claim MUST be represented during this step by an assertion using the same label as the final *<<_identity_assertion,identity assertion>>.* The content of the _<<_placeholder_assertion,placeholder assertion>>_ is unimportant, except that the size in bytes of the _<<_placeholder_assertion,placeholder assertion>>_ MUST be large enough to accommodate the final *<<_identity_assertion,identity assertion>>.*
2. link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_adding_assertions_and_redactions++[Section 10.3.2.1, “Adding assertions and redactions”]
3. link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_adding_ingredients++[Section 10.3.2.2, “Adding ingredients”]
4. link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_connecting_the_signature++[Section 10.3.2.3, “Connecting the signature”]
5. If using C2PA 1.x process, link:++https://c2pa.org/specifications/specifications/1.4/specs/C2PA_Specification.html#_prepare_the_xmp++[Section 11.4.1, “Prepare the XMP”].
6. link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_create_content_bindings++[Section 10.4.1, “Create content bindings”]
7. The list of _<<_referenced_assertions,referenced assertions>>_ (including the _<<_hard_binding,hard binding>>_ assertion) MUST be presented to the _<<_credential_holder,credential holder>>_ for each *<<_identity_assertion,identity assertion>>* to be added, as described in xref:_presenting_the_signer_payload_data_structure_for_signature[xrefstyle=full] by the corresponding _<<_credential_holder,credential holder>>._ Once each signature has been obtained, the _<<_placeholder_assertion,placeholder assertion>>_ content MUST be replaced with the final *<<_identity_assertion,identity assertion>>* content incorporating that signature. The _<<_identity_assertion_generator,identity assertion generator>>_ SHOULD independently validate the signature from the _<<_credential_holder,credential holder>>_ before proceeding.
8. The remaining steps from link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_multiple_step_processing++[Section 10.4, “Multiple step processing,”] MUST now be completed.
9. link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_signing_a_claim++[Section 10.3.2.4, “Signing a claim”]
10. link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_time_stamps++[Section 10.3.2.5, “Time stamps”]
11. link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_credential_revocation_information++[Section 10.3.2.6, “Credential revocation information”]

These steps are also represented by the following sequence diagram, which is non-normative:

[mermaid,width=100%]
....
sequenceDiagram
    participant G as Identity assertion generator
    participant H as Credential holder

    G->>G: Create assertions
    Note right of G: Includes placeholder assertions
    G->>G: Create content bindings
    
    loop For each credential holder
    G->>H: Request signature over list of referenced assertions
    H->>G: Provide signature over list of referenced assertions
    G->>G: Independently verify signature
    end

    G->>G: Replace placeholder assertions with final identity assertions
    G->>G: Create claim
    G->>G: Issue claim generator signature for final claim
    G->>G: Create manifest store
....

== Validating the identity assertion

=== Validation method

IMPORTANT: Validation of the _<<C2PA Manifest>>_ MUST be completed with a finding that the manifest is at least _well-formed_ as per link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_well_formed_manifest++[Section 14.3.2, Well-formed manifest,”] of the C2PA technical specification before a validator attempts to report on the validity of an *<<_identity_assertion,identity assertion>>.*

An *<<_identity_assertion,identity assertion>>* MUST contain a valid CBOR data structure that contains the required fields as documented in the `identity` rule in xref:_cbor_schema[xrefstyle=full]. The `cawg.identity.cbor.invalid` error code SHALL be used to report assertions that do not follow this rule. A validator SHALL NOT consider any extra fields not documented in the `identity` rule during the validation process.

NOTE: Extra fields can be read and processed in non-validation scenarios.

For each entry in `signer_payload.referenced_assertions`, the validator MUST verify that the same entry exists in either the `created_assertions` or `gathered_assertions` entry of the _<<C2PA claim>>._ (For version 1 claims, the entry must appear in the `assertions` entry.) The `cawg.identity.assertion.mismatch` error code SHALL be used to report violations of this rule.

The validator SHOULD verify that no entry in `signer_payload.referenced_assertions` is duplicated. The `cawg.identity.assertion.duplicate` error code SHALL be used to report violations of this rule.

The validator MUST ensure that `signer_payload.referenced_assertions` contains at least one _<<_hard_binding,hard binding>>_ assertion as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hard_bindings++[Section 9.2, “Hard bindings”] of the C2PA technical specification. The `cawg.identity.hard_binding_missing` error code SHALL be used to report a missing _<<_hard_binding,hard binding>>_ assertion.

The validator MUST maintain a list of valid `signer_payload.sig_type` values and corresponding code paths for the `signature` values that it is prepared to accept. Validators SHOULD be prepared to accept all signature types described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full]. The `cawg.identity.sig_type.unknown` error code SHALL be used to report assertions that contain unrecognized `signer_payload.sig_type` values.

The `signature` field of an *<<_identity_assertion,identity assertion>>* MUST contain a valid signature. The procedure for validating each signature type and corresponding status codes are described in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

The `pad1` and `pad2` fields of an *<<_identity_assertion,identity assertion>>* MUST contain only zero-value (`0x00`) bytes. The `cawg.identity.pad.invalid` error code SHALL be used to report assertions that contain other values in these fields.

==== Validating the `expected_partial_claim` field

If the *<<_identity_assertion,identity assertion>>* contains an `expected_partial_claim` field in `signer_payload`, it MUST be validated as follows:

. Locate the _<<C2PA claim>>_ data structure that includes this *<<_identity_assertion,identity assertion>>.*
. Replace the `hash` value for the specific *<<_identity_assertion,identity assertion>>* being validated with all zero-value (`0x00`) bytes.
. If the *<<_identity_assertion,identity assertion>>* contains an `expected_countersigners` field in `signer_payload`, for each entry in the `expected_countersigners` array where an *<<_identity_assertion,identity assertion>>* can be found that matches the signing credentials used as described in xref:_serialization_for_credential_types[], replace the `hash` field for that *<<_identity_assertion,identity assertion>>* being validated with all zero-value (`0x00`) bytes.
. Serialize the updated _<<C2PA claim>>_ data structure using link:++https://www.rfc-editor.org/rfc/rfc8949.html#name-core-deterministic-encoding++[Section 4.2.1, “Core deterministic encoding,”] of RFC 8949: Concise binary object representation.
. Compute a hash of the serialized _<<C2PA claim>>_ data structure using the hash algorithm described by `expected_partial_claim.alg`.

The resulting hash MUST exactly match the value present in `expected_partial_claim.hash`. The `cawg.identity.expected_partial_claim.mismatch` error code SHALL be used to report assertions that contain other values.

==== Validating the `expected_claim_generator` field

If the *<<_identity_assertion,identity assertion>>* contains an `expected_claim_generator` field in `signer_payload`, it MUST be validated as follows:

. Locate the end-entity signing certificate that is present in the _<<C2PA claim>>_ signature. It can be located as described in link:https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#x509_certificates[Section 14.6, “X.509 certificates,”] of the C2PA technical specification.
. Identify the CBOR bytes specific to this signing certifcate. If necessary, any re-serialization should be performed using link:++https://www.rfc-editor.org/rfc/rfc8949.html#name-core-deterministic-encoding++[Section 4.2.1, “Core deterministic encoding,”] of RFC 8949: Concise binary object representation.
. Compute a hash of the serialized end-entity certificate using the hash algorithm described by `expected_claim_generator.alg`.

The resulting hash MUST exactly match the value present in `expected_claim_generator.hash`. The `cawg.identity.expected_claim_generator.mismatch` error code SHALL be used to report assertions that contain other values.

==== Validating the `expected_countersigners` field

If the *<<_identity_assertion,identity assertion>>* contains an `expected_countersigners` field in `signer_payload`, it MUST be validated as follows:

. For every _other_ *<<_identity_assertion,identity assertion>>* that is present in the <<C2PA Manifest>>:
.. Find the `signer_payload` map in that *<<_identity_assertion,identity assertion>>*. Remove any `expected_countersigners` field that is found in that `signer_payload` map. This will be referred to in the rest of this process as the _partial signer payload._
.. Search the `expected_countersigners` list _in the current *<<_identity_assertion,identity assertion>>* being validated_ for an entry where `partial_signer_payload` matches the just-computed _partial signer payload._ If no such entry can be found, stop validating and return the `cawg.identity.unexpected_countersigner` error code.
.. If the entry in `expected_countersigners` also contains an `expected_credentials` entry:
... Serialize the signing credential as a CBOR byte string as described in xref:_serialization_for_credential_types[]. This serialization should be performed using link:++https://www.rfc-editor.org/rfc/rfc8949.html#name-core-deterministic-encoding++[Section 4.2.1, “Core deterministic encoding,”] of RFC 8949: Concise binary object representation.
... Compute a hash of the serialized signing credential using the algorithm specified by the `alg` entry in the `expected_credentials` map.
... Compare the just-computed hash with the `hash` entry in the `expected_credentials` map. If they do not match, stop validating and return the `cawg.identity.expected_countersigner.mismatch` error code.
. If any entry exists in `expected_countersigners` that was not matched by the previous loop, the `cawg.identity.expected_countersigner.missing` error code SHOULD be returned.

=== Status codes

The set of standard success and failure codes for *<<_identity_assertion,identity assertion>>* validations are defined below. These follow the format defined by the section titled link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_returning_validation_results++[Section 15.2, Returning validation results,”] of the C2PA technical specification.

The `url` field for a status code MUST always be the label of the *<<_identity_assertion,identity assertion>>.* It is omitted from the tables below.

==== Success codes

[width="100%",cols="4,10",options="header"]
|=======================
| Value        |   Meaning
|`cawg.identity.trusted` | The *<<_identity_assertion,identity assertion>>,* including the referenced credentials and signature binding the _<<_credential_holder,credential holder>>_ to the _<<C2PA claim>>_, is validated. The _<<_named_actor,named actor>>_ is considered *trusted* according to the evaluation in xref:_trust_scenarios_in_identity_assertion[xrefstyle=full].
|`cawg.identity.well-formed` | The *<<_identity_assertion,identity assertion>>,* including the referenced credentials and signature binding the _<<_credential_holder,credential holder>>_ to the _<<C2PA claim>>_, is validated. The evaluation in xref:_trust_scenarios_in_identity_assertion[xrefstyle=full] could not identify any root of trust for the _<<_named_actor,named actor>>._
|=======================

==== Failure codes

[width="100%",cols="4,10",options="header"]
|=======================
| Value        |   Meaning
|`cawg.identity.cbor.invalid` | The CBOR of the *<<_identity_assertion,identity assertion>>* is not valid.
|`cawg.identity.assertion.mismatch` | The *<<_identity_assertion,identity assertion>>* contains an assertion reference that could not be found in the _<<C2PA claim>>._
|`cawg.identity.assertion.duplicate` | The *<<_identity_assertion,identity assertion>>* contains one or more duplicate assertion references.
|`cawg.identity.credential_revoked` | The *<<_identity_assertion,identity assertion>>* was signed using a _<<_credential_revocation,revoked credential>>._
|`cawg.identity.hard_binding_missing` | The *<<_identity_assertion,identity assertion>>* does not reference a _<<_hard_binding,hard binding>>_ assertion.
|`cawg.identity.sig_type.unknown` | The `signer_payload.sig_type` of the *<<_identity_assertion,identity assertion>>* is not recognized.
|`cawg.identity.pad.invalid` | The `pad1` or `pad2` field contains non-zero bytes.
|`cawg.identity.expected_partial_claim.mismatch` | The `signer_payload.expected_partial_claim` field did not match the _<<C2PA claim>>_ data structure.
|`cawg.identity.expected_claim_generator.mismatch` | The `signer_payload.expected_claim_generator` field did not match the X.509 certificate used to sign the _<<C2PA claim>>._ 
|`cawg.identity.unexpected_countersigner` | An *<<_identity_assertion,identity assertion>>* exists in this _<<C2PA Manifest>>_ that was not described in `signer_payload.expected_countersigners`
|`cawg.identity.expected_countersigner.mismatch` | An *<<_identity_assertion,identity assertion>>* exists in this _<<C2PA Manifest>>_ that has the expected `signer_payload` but has different signing credentials than were described in `signer_payload.expected_countersigners`
|``cawg.identity.expected_countersigner.missing` | The `signer_payload.expected_countersigners` describes an *<<_identity_assertion,identity assertion>>* that does not exist in this _<<C2PA Manifest>>_
|=======================

NOTE: Additional failure codes relating to specific signature types are defined in xref:_credentials_signatures_and_validation_methods[xrefstyle=full].

== Credentials, signatures, and validation methods

The *<<_identity_assertion,identity assertion>>* allows multiple signature types to be represented, although only one _<<ToIP verifiable identifier>>_ and corresponding signature can be used in any single assertion.

The signature type is represented by the `signer_payload.sig_type` field. Some credential types are described in this specification. It is strongly recommended that *<<_identity_assertion,identity assertion>>* validators be prepared to read all of the signature types described in this specification.

Other specifications MAY define additional `signer_payload.sig_type` values and the corresponding definition of `signature`, subject to restrictions described in xref:_labels[xrefstyle=full].

[IMPORTANT]
.Credential types in minor version updates
====
Future minor version updates (1.1, 1.2, etc.) to this specification MAY:

1. Add new sections to this specification defining new credential types and their corresponding `signer_payload.sig_type` values.
2. Mark existing sections of this specification defining existing credential types and their corresponding `signer_payload.sig_type` values as deprecated.

Such updates to the specification SHOULD continue to use the `cawg.identity` assertion label.
====

=== Identity claims aggregation

==== Identity claims aggregation conceptual overview

_This section is non-normative._

Content creators (_<<_named_actor,named actors>>_) may wish to document their role in creating a _<<C2PA asset>>_ using identity signals that are commonly understood in the mass market. Examples of such signals include:

* verified web sites
* social media accounts
* official ID documentation
* professional accreditations
* organizational affiliations

These common identity signals, though popular, are not well-designed for use as lasting identifiers. Some of the challenges associated with these identity signals include:

* The methods for accessing, describing, and presenting these signals are widely disparate.
* These signals typically do not provide the ability to issue signatures on the _<<_named_actor,named actor’s>>_ behalf.
* The verification methods associated with these signals are typicially designed for momentary validation; they typically do not provide artifacts that can be independently verified at an arbitrary time (perhaps months or years after issuance).

To facilitate the use of such identity signals, the _<<_named_actor,named actor>>_ may use the services of a third-party intermediary that they trust to gather these signals and to restate them on their behalf.

We call this intermediary an *<<_identity_claims_aggregator,identity claims aggregator>>.* It performs two important roles:

1. It collects and verifies identity attestation claims from various _<<_identity_provider,identity providers>>_ such as social media sites and ID verification vendors.
2. When the _<<_named_actor,named actor>>_ creates content, it creates a unique asset-specific credential binding the identity attestation claims collected earlier to the specific _<<C2PA asset>>_ being described.

IMPORTANT: An *identity claims aggregation* claim does not support a _<<_named_actor,named actor>>_ using their own credential to directly issue their own signature for an *<<_identity assertion,identity assertion>>.* This may be added in a future version of this specification.

The two workflows performed by the _<<_identity_claims_aggregator,identity claims aggregator>>_ are described in the sections below:

===== Providing identity claims to identity claims aggregator

In the first workflow, the _<<_named_actor,named actor>>_ asks the _<<_identity_claims_aggregator,identity claims aggregator>>_ to verify an identity claim. The _<<_identity_claims_aggregator,identity claims aggregator>>_ contacts the _<<_identity_provider,identity provider>>_ to verify the identity claim. If that verification is successful, the _<<_identity_claims_aggregator,identity claims aggregator>>_ remembers the provided information for later use on the _<<_named_actor,named actor’s>>_ behalf.

[#ica-workflow-gathering-claims]
****
.Gathering identity claims
image::identity-claims-aggregation/verifying-identity-attestations.drawio.svg[Gathering identity claims,width=430,height=320,align="center"]
****

This workflow can be repeated any number of times to provide additional identity signals for the _<<_named_actor,named actor>>._

===== Creating content using the aggregated identity claims

Once the _<<_identity_claims_aggregator,identity claims aggregator>>_ has verified one or more identity signals, the _<<_named_actor,named actor>>_ can then use an authoring tool to create content. This authoring tool collaborates with the _<<_identity_claims_aggregator,identity claims aggregator>>_ to attach the identity claims which have been aggregated to date to the _<<C2PA asset>>_ being created.

[#ica-workflow-creating content]
****
.Creating content using identity claims
image::identity-claims-aggregation/creating-content.drawio.svg[Creating content using identity claims,width=570,height=410,align="center"]

****

This workflow can be repeated any number of times to create new content on behalf of the _<<_named_actor,named actor>>._

===== Interpreting an identity assertion using identity claims aggregation

At some later time, an _<<_identity_assertion_consumer,identity assertion consumer>>_ will interpret this *<<_identity assertion,identity assertion>>.* Assuming that the _<<_identity_assertion,identity assertion>>_ is deemed valid and from a trustworthy source, the content of the assertion should be interpreted as follows:

[quote,Signed by identity claims aggregator]
____
The _<<_named_actor,named actor>>_ described by this credential has presented one or more identity signals to this _<<_identity_claims_aggregation,identity claims aggregation>>_ service. Those claims were verified and deemed valid by this service as of the times indicated in the credential.

The signature on the credential indicates that the _<<_identity_claims_aggregator,identity claims aggregator>>_ attests that this same _<<_named_actor,named actor>>_ has presented the _<<C2PA asset>>_ described by this _<<C2PA Manifest>>_ to this service and has claimed a role in the production of said asset.
____

==== Identity claims aggregation technical description

The _<<_identity_claims_aggregator,identity claims aggregator>>_ will produce a specific type of _<<_W3C verifiable credential,W3C verifiable credential>>_ called an “identity claims aggregation” that binds the identity attestation claims to the _<<C2PA asset>>._ This credential, once signed with the _<<_identity_claims_aggregator,identity claims aggregator’s>>_ private key, is the `signature` value for the *<<_identity_assertion,identity assertion>>.* The signature value is further described in xref:_verifiable_credential_proof_mechanism[xrefstyle=full].

The `signer_payload.sig_type` value for such an assertion MUST be `cawg.identity_claims_aggregation`.

The trust model in this scenario is as described in xref:_named_actor_without_signature_authority[xrefstyle=full].

An *identity claims aggregation* MUST meet all requirements for a verifiable credential as described in https://www.w3.org/TR/vc-data-model-2.0/[Verifiable credentials data model, version 2.0], and additional requirements as stated in the remainder of this section:

[#vc-property-context]
===== Context

The `@context` property MUST be present and MUST contain at least the following two entries:

* `https://www.w3.org/ns/credentials/v2`
* `https://creator-assertions.github.io/tbd/tbd`

[#issue-145]
NOTE: TO DO (link:https://github.com/creator-assertions/identity-assertion/issues/145[issue #145]): Transition the identity claims aggregation context to the recently-acquired domain cawg.io once it is provisioned and ready to use.

[#vc-property-type]
===== Type

The `type` property MUST be present and MUST contain at least the following two entries:

* `VerifiableCredential`
* `IdentityClaimsAggregationCredential`

[#vc-property-issuer]
===== Issuer

The `issuer` property MUST be present and MUST follow the format as specified in link:++https://www.w3.org/TR/vc-data-model-2.0/#issuer++[Section 4.7, “Issuer,”] of the Verifiable credentials data model.

[#vc-property-validFrom]
===== Validity

The `validFrom` field MUST exist and it MUST express the date and time when the credential becomes valid, as specified in link:++https://www.w3.org/TR/vc-data-model-2.0/#validity-period++[Section 4.8, “Validity period,”] of the Verifiable credentials data model.

[#vc-credentialsubject-verifiedIdentities]
===== Verified identities

The `verifiedIdentities` property MUST be present and MUST be a non-empty array. Every item in the array MUST contain information about the _<<_named_actor,named actor>>_ as verified by the _<<_identity_assertion_generator,identity assertion generator>>_ or a service contacted by the _<<_identity_assertion_generator,identity assertion generator>>._

.Example:
[source,json]
----
"credentialSubject": {
  ...
  "verifiedIdentities": [
    {
      "name": "First-Name Last-Name",
      "type": "cawg.document_verification",
      "provider": {
        "id": "https://example-id-verifier.com",
        "name": "Example ID Verifier",
      },
      "verifiedAt": "2024-07-26T22:30:15Z"
    },
    {
      "type": "cawg.domain_control_validation",
      "uri": "named-actor-site.example",
      "dns_txt": "c0b8f1cf41784976a646ff012766076f",
      "verifiedAt": "2024-09-25T22:13:35Z"
    },
    {
      "type": "cawg.affiliation",
      "provider": {
        "id": "https://example-affiliated-organization.com",
        "name": "Example Affiliated Organization",
      },
      "verifiedAt": "2024-07-26T22:29:57Z"
    },
    {
      "type": "cawg.social_media",
      "name": "Silly Cats 929",
      "username": "username",
      "uri": "https://example-social-network.com/username",
      "provider": {
        "id": "https://example-social-network.com",
        "name": "Example Social Network"
      },
      "verifiedAt": "2024-05-27T08:40:39.569856Z"
    },
    {
      "type": "cawg.crypto_wallet",
      "address": "fa64ef445f994138bdeb9baac6ce1e16",
      "uri": "https://example-crypto-wallet.com/fa64ef445f994138bdeb9baac6ce1e16",
      "provider": {
        "id": "https://example-crypto-wallet.com",
        "name": "Example Crypto Wallet"
      },
      "verifiedAt": "2024-05-27T08:40:39.569856Z"
    }
  ]
  ...
}
----

[#vc-credentialsubject-verifiedidentity-type]
====== Verified identity type

The `verifiedIdentities[?].type` property MUST be present and MUST be a non-empty string that defines the type of verification that was performed by the _<<_identity_provider,identity provider>>._ This specification defines the following values which _<<_identity_assertion_consumer,identity assertion consumers>>_ SHOULD be prepared to accept:

[width="100%",cols="4,10",options="header"]
|=======================
| Value        |  Meaning
| `cawg.document_verification` | The _<<_identity_provider,identity provider>>_ has verified one or more government-issued identity documents presented by the _<<_named_actor,named actor>>._
| `cawg.domain_control_validation` | The _<<_named_actor,named actor>>_ has proven control over a specific domain to the _<<_identity_claims_aggregator,identity claims aggregator>>._
| `cawg.affiliation` | The _<<_identity_provider,identity provider>>_ is attesting to the _<<_named_actor,named actor’s>>_ membership in an organization. This could be a professional organization or an employment relationship.
| `cawg.social_media` | The _<<_named_actor,named actor>>_ has demonstrated control over an account (typically a social media account) hosted by the _<<_identity_provider,identity provider>>._
| `cawg.crypto_wallet` | The _<<_named_actor,named actor>>_ has demonstrated control over an account (typically a crypto-wallet) hosted by the _<<_identity_provider,identity provider>>._ 
|=======================

Other string values MAY be used in `verifiedIdentities[?].type`, subject to restrictions described in xref:_labels[xrefstyle=full].

[#vc-credentialsubject-verifiedidentity-name]
====== Display name

The `verifiedIdentities[?].name` property MAY be present. If present, it MUST NOT be empty and must be a string defining the _<<_named_actor,named actor’s>>_ name as understood by the _<<_identity_provider,identity provider>>._

If the `type` of this verified identity is `cawg.document_verification`, the `verifiedIdentities[?].name` property MUST be present and MUST exactly match the name found on the identity documents.

[#vc-credentialsubject-verifiedidentity-username]
====== User name

The `verifiedIdentities[?].username` property MAY be present. If present, it MUST be a non-empty text string representing the _<<_named_actor,named actor’s>>_ user name as assigned by the _<<_identity_provider,identity provider>>._

If the `type` of this verified identity is `cawg.social_media`, the `verifiedIdentities[?].username` property MUST be present and MUST be the unique alphanumeric string that can be used to identity the _<<_named_actor,named actor>>_ within this service.

[#vc-credentialsubject-verifiedidentity-address]
====== Address

The `verifiedIdentities[?].address` property MAY be present. If present, it MUST be a non-empty text string representing the _<<_named_actor,named actor’s>>_ cryptographic address as assigned by the _<<_identity_provider,identity provider>>._

If the `type` of this verified identity is `cawg.crypto_wallet`, the `verifiedIdentities[?].address` property MUST be present and MUST be the unique alphanumeric string that can be used to identity the _<<_named_actor,named actor>>_ within this service.

[#vc-credentialsubject-verifiedidentity-uri]
====== URI

The `verifiedIdentities[?].uri` property MAY be present. If present, it must be a valid URI which is the primary point of contact for the _<<_named_actor,named actor>>_ as assigned by the _<<_identity_provider,identity provider>>._

If the `type` of this verified identity is `cawg.domain_control_validation`, the `verifiedIdentities[?].uri` property MUST be present and must be the primary web URI for the _<<_named_actor,named actor’s>>_ web site as validated by the _<<_identity_claims_aggregator,identity claims aggregator>>._ Additionally, one of the following fields SHOULD be present to allow the _<<_identity_assertion_consumer,identity assertion consumer>>_ the ability to independently verify continued control over the domain:

* `dns_txt`: a random string value generated by the  _<<_identity_assertion_consumer,identity assertion consumer>>_ and placed by the _<<_named_actor,named actor>>_ in the domain’s DNS as a `TXT` record

NOTE: TO DO: Consider supporting other domain control validation methods (`meta` tags? `CNAME` records? etc.?)

If the `type` of this verified identity is `cawg.social_media`, it is RECOMMENDED that the `verifiedIdentities[?].uri` be the primary web URI for the _<<_named_actor,named actor’s>>_ social media account.

[#vc-credentialsubject-verifiedidentity-verifiedat]
====== Identity verification date

The `verifiedIdentities[?].verifiedAt` MUST be present and MUST be a valid date-time as specified by link:https://datatracker.ietf.org/doc/html/rfc3339[RFC 3339]. It represents the date and time when the relationship between the _<<_named_actor,named actor>>_ and the _<<_identity_provider,identity provider>>_ was verified by the _<<_identity_assertion_generator,identity assertion generator>>._

[#vc-credentialsubject-verifiedidentity-provider]
====== Identity provider details

The `verifiedIdentities[?].provider` property MUST be an object and MUST be present. It contains details about the _<<_identity_provider,identity provider>>_ and the identity verification process. This specification mentions at least two properties that MAY be used to represent the _<<_named_actor,named actor’s>>_ verification details: `id` and `name`.

[#vc-credentialsubject-verifiedidentity-provider-id]
Identity provider ID::
The `verifiedIdentities[?].provider.id` MUST be present and MUST be a valid URI that, when dereferenced, MUST result in a proof of authenticity of the _<<_identity_provider,identity provider>>._ This proof of authenticity of the _<<_identity_provider,identity provider>>_ MUST NOT be confused with the proof of verification of the _<<_named_actor,named actor>>._

[#vc-credentialsubject-verifiedidentity-provider-name]
Identity provider name::
The `verifiedIdentities[?].provider.name` MUST be present and MUST be a _<<_natural_language_string,natural language string>>._ The `verifiedIdentities[?].provider.name` property is the name of the _<<_identity_provider,identity provider>>._

===== Binding to C2PA asset

The `credentialSubject` field MUST contain a `c2paAsset` entry, which MUST be the JSON serialization of the `signer_payload` data structure presented for signature with the following adaptations:

* All CBOR bytestring values in `signer_payload` data structure (for example, `hash` entries in the hashlink data structure) MUST be converted to the corresponding base 64 encoding as specified in link:++https://datatracker.ietf.org/doc/html/rfc4648#section-4++[Section 4, “Base 64 Encoding,”] of RFC 4648. The base 64 encoding MUST NOT use the URL-safe variation of base 64. The encoding MUST NOT include line feeds or additional annotations not directly required by the core base 64 specification.
* The JSON encoding MUST use the field names exactly as specified in xref:_overview[xrefstyle=full].
+
IMPORTANT: Field names in the `signer_payload` data structure (see xref:_overview[xrefstyle=full]) are specified using lower-case letters with underscore characters (commonly referred to as `snake_case`). Field names in the verifiable credential data model are typically specified using lower-case letters with upper-case letters for word breaks (commonly referred to as `camelCase`). A translation between the two styles MUST NOT be performed as it creates the potential for miscommunication.

[#example-c2pa-asset-section]
.`c2paAsset` entry
[example]
====
[source,json]
----
"credentialSubject": {
  ...
  "c2paAsset": {
    ...
    "referenced_assertions": [
      {
        "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.hash.data",
        "hash": "U9Gyz05tmpftkoEYP6XYNsMnUbnS/KcktAg2vv7n1n8="
      },
      {
        "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.thumbnail.claim.jpeg",
        "hash": "G5hfJwYeWTlflxOhmfCO9xDAK52aKQ+YbKNhRZeq92c="
      },
      {
        "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.ingredient.v2",
        "hash": "Yzag4o5jO4xPyfANVtw7ETlbFSWZNfeM78qbSi8Abkk="
      }
    ],
    "sig_type": "cawg.identity_claims_aggregation"
    ...
  }
  ...
}
----
====

==== Identity claims aggregation verifiable credential example

An example of the *<<_identity_claims_aggregation,identity claims aggregation>>* verifiable credential is given below:

.Identity claims aggregation verifiable credential
[#example-ia-vc]
[example]
====
[source,json]
----
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    "https://creator-assertions.github.io/tbd/tbd"
  ],
  "type": [
    "VerifiableCredential",
    "IdentityClaimsAggregationCredential"
  ],
  "issuer": "did:web:connected-identities.identity.adobe.com",
  "validFrom": "2024-05-27T11:40:40Z",
  "credentialSubject": {
    "id": "did:web:connected-identities.identity.adobe.com:user:jsadkfnaksdnj",    
    "verifiedIdentities": [
      {
        "name": "First-Name Last-Name",
        "type": "cawg.document_verification",
        "provider": {
          "id": "https://example-id-verifier.com",
          "name": "Example ID Verifier",
        },
        "verifiedAt": "2024-07-26T22:30:15Z"
      },
      {
        "type": "cawg.affiliation",
        "provider": {
          "id": "https://example-affiliated-organization.com",
          "name": "Example Affiliated Organization",
        },
        "verifiedAt": "2024-07-26T22:29:57Z"
      },
      {
        "type": "cawg.social_media",
        "name": "Silly Cats 929",
        "username": "username",
        "uri": "https://example-social-network.com/username",
        "provider": {
          "id": "https://example-social-network.com",
          "name": "Example Social Network"
        },
        "verifiedAt": "2024-05-27T08:40:39.569856Z"
      },
      {
        "type": "cawg.crypto_wallet",
        "username": "username",
        "uri": "https://example-crypto-wallet.com/username",
        "provider": {
          "id": "https://example-crypto-wallet.com",
          "name": "Example Crypto Wallet"
        },
        "verifiedAt": "2024-05-27T08:40:39.569856Z"
      }
    ],
    "c2paAsset": {
      "referenced_assertions": [
        {
          "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.hash.data",
          "hash": "U9Gyz05tmpftkoEYP6XYNsMnUbnS/KcktAg2vv7n1n8="
        },
        {
          "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.thumbnail.claim.jpeg",
          "hash": "G5hfJwYeWTlflxOhmfCO9xDAK52aKQ+YbKNhRZeq92c="
        },
        {
          "url": "self#jumbf=c2pa/urn:uuid:F9168C5E-CEB2-4faa-B6BF-329BF39FA1E4/c2pa.assertions/c2pa.ingredient.v2",
          "hash": "Yzag4o5jO4xPyfANVtw7ETlbFSWZNfeM78qbSi8Abkk="
        }
      ],
      "sig_type": "cawg.identity_claims_aggregation"
    },
  },
  "credentialSchema": [
    {
      "id": "https://creator-assertions.github.io/schemas/v1/identity-claims-aggregation.json",
      "type": "JSONSchema"
    }
  ]  
}
----
====

[#issue-152]
NOTE: TO DO (link:https://github.com/creator-assertions/identity-assertion/issues/152[issue #152]): Track changes to draft schema and ensure example is correctly updated.

==== Data verification schema

The *<<_identity_assertion,identity assertion>>* verifiable credential must adhere to a set of strict requirements as depicted in xref:_identity_claims_aggregation_description[xrefstyle=full]. All of these requirements are gathered in a https://www.w3.org/TR/vc-json-schema/[verifiable credentials JSON schema], i.e. `https://creator-assertions.github.io/schemas/v1/identity-claims-aggregation.json`. This JSON schema SHOULD be used to establish if the structure and contents of a verifiable credential conforms to all *<<_identity_assertion,identity assertion>>* verifiable credential requirements.

[#issue-153]
NOTE: TO DO (link:https://github.com/creator-assertions/identity-assertion/issues/153[issue #153]): Update schema URL once it is finalized.

[#issue-154]
NOTE: TO DO (link:https://github.com/creator-assertions/identity-assertion/issues/154[issue #154]): Add text explaining the use of `credentialSchema` property as per the example below.

[source,json]
----
"credentialSchema": [
  {
    "id": "https://creator-assertions.github.io/schemas/v1/identity-claims-aggregation.json",
    "type": "JSONSchema"
  }
]
----

NOTE: The usage of this data verification schema is not enforced by this specification, but it is RECOMMENDED to be used when possible.

==== Recommendations for issuers

NOTE: TO DO (link:https://github.com/creator-assertions/identity-assertion/issues/154[issue #154]): Merge with above section? This explains the use of `credentialSchema` to answer my earlier TO DO item.

The inclusion of the `credentialSchema` property in a verifiable credential is OPTIONAL. However, it is highly recommended to include this field to specify the structure and constraints of the credential’s data.

The inclusion of the `identity-claims-aggregation.json` schema in the verifiable credential `credentialSchema` is OPTIONAL. However, it is RECOMMENDED to include it as it enforces this specification’s constraints.

==== Recommendations for verifiers

The usage of the data verification schemas from a verifiable credential’s `credentialSchema` is OPTIONAL. However, it is RECOMMENDCED that verifiers use the `credentialSchema` to validate the structure and data integrity of the verifiable credential. By referencing the schemas specified in the `credentialSchema` field, verifiers can ensure that the credential data adheres to the expected format and rules.

NOTE: `identity-claims-aggregation.json` makes use of the `format` JSON Schema keyword. If used, the JSON Schema processor must enable the `format` usage.

==== Verifiable credential proof mechanism

The `signature` field of an *<<_identity_assertion,identity assertion>>* using the identity claim aggregation mechanism MUST be secured using a COSE signature as described by link:++https://www.w3.org/TR/vc-jose-cose/#securing-vcs-with-cose++[Section 3.3.1, “Securing JSON-LD verifiable credentials with COSE,”] of the W3C standard _Securing verifiable credentials using JOSE and COSE._ The `signature` payload MUST begin with the tagged `COSE_Sign1` structure. As described in that standard, the unsecured verifiable credential is the unencoded `COSE_Sign1` payload.

The COSE signature MAY use a link:https://datatracker.ietf.org/doc/html/rfc3161[RFC 3161]-compliant time stamp to provide an additional, independent signal as to when the _<<_identity_claims_aggregator,identity claims aggregator>>_ generated the *<<_identity_assertion,identity assertion>>.* If so, this time stamp shall be generated as described by link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_time_stamps++[Section 10.3.2.5, “Time-stamps,”] of the C2PA technical specification.

IMPORTANT: If a timestamp is present, it MUST use a version 2 or later time-stamp as defined in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload.”] A version 1 time stamp MUST NOT be used.

If the _<<_identity_claims_aggregator,identity claims aggregator’s>>_ credential supports querying its online credential status, the _<<_identity_claims_aggregator,identity claims aggregator>>_ SHOULD include credential revocation information as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_credential_revocation_information++[Section 10.3.2.6, “Credential revocation information,”] of the C2PA technical specification.

===== Signature algorithms

The COSE signature MUST be secured using one of the signature algorithms defined in link:++https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital signatures,”] in version 2.1 or any subsequent version of the C2PA technical specification.

===== DID methods

The public key corresponding to the `issuer` field SHALL be discoverable using one of the link:++https://www.w3.org/TR/did-core/#dfn-did-methods++[DID methods] as described in this section. This section defines:

* A list of DID methods that are allowed for providing public keys for new content as well as required for discovering public keys for existing content (the allowed list);
* A list of DID methods that are required to be supported for discovering public keys for existing content but are not allowed for providing keys for of new content (the deprecated list).

A DID method SHALL appear in no more than one list. If a DID method does not appear in either list, it is forbidden and MUST NOT be used or supported. Algorithms can be removed from the lists in order to implement forbidding a DID method. For this reason, implementations SHALL NOT support additional DID methods on an optional basis.

Implementers SHOULD consult this section in the current version of this specification when releasing software updates and ensure their supported DID methods conform to it.

The allowed list is:

* link:https://w3c-ccg.github.io/did-method-web/[`did:web`]

The deprecated list is empty.

==== Validating an identity assertion with verifiable credentials

[#issue-156]
NOTE: TO DO (link:https://github.com/creator-assertions/identity-assertion/issues/156[issue #156]): Write section on validating.

=== X.509 certificates and COSE signatures

In some use cases, an _<<_actor,actor>>_ in the system MAY wish to provide an _https://tools.ietf.org/html/rfc5280[X.509 certificate]_ to have an organizational or individual identity described by the certificate associated with the list of _<<_referenced_assertions,referenced assertions>>._

The `signer_payload.sig_type` value for such an assertion MUST be `cawg.x509.cose`. The `signature` value MUST be a _https://datatracker.ietf.org/doc/html/rfc8152[COSE signature]_ as described below.

==== Generating the COSE signature

To generate the COSE signature for an *<<_identity_assertion,identity assertion>>,* the steps described in the listed sections of the C2PA technical specification MUST be followed with adaptations as described subsequently:

* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_signing_a_claim++[Section 10.3.2.4, “Signing a claim”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_time_stamps++[Section 10.3.2.5, “Time-stamps”]
+
IMPORTANT: An *<<_identity_assertion,identity assertion>>* MUST NOT contain a v1 time-stamp as defined in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload.”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_credential_revocation_information++[Section 10.3.2.6, “Credential revocation information”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_hashing++[Section 13.1, “Hashing”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_digital_signatures++[Section 13.2, “Digital signatures”]

In each of the above sections, the following changes MUST be applied:

* Any reference to the _claim_ MUST be replaced with the CBOR serialization of the `signer_payload` field from the *<<_identity_assertion,identity assertion>>.* The `signer_payload` data structure MUST be serialized as described in link:++https://www.rfc-editor.org/rfc/rfc8949.html#name-core-deterministic-encoding++[Section 4.2.1, “Core Deterministic Encoding,”] of RFC 8949: Concise Binary Object Representation. The resulting byte string is presented to the _<<_credential_holder,credential holder>>_ for signature.
* Any reference to the _claim generator_ MUST be replaced with the _<<_actor,actor>>_ whose _X.509 certificate_ is being used for this assertion.

==== Validating the COSE signature

To validate the COSE signature for an *<<_identity_assertion,identity assertion>>,* the steps described in the listed sections of the C2PA technical specification MUST be followed with adaptations as described:

* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_validate_the_signature++[Section 15.5, “Validate the signature.”] Disregard the paragraph that starts with “Retrieve the URI reference.” Instead retrieve the COSE signature from the `signature` field of the *<<_identity_assertion,identity assertion>>.*
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_validate_the_time_stamp++[Section 15.6, “Validate the time-stamp”]
* link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_validate_the_credential_revocation_information++[Section 15.7, “Validate the credential revocation information”]

In each of the above sections, the following changes MUST be applied:

* Any reference to the _claim_ MUST be replaced with the CBOR serialization of the `signer_payload` field from the *<<_identity_assertion,identity assertion>>.*
* Any reference to the _claim generator_ MUST be replaced with the _<<_actor,actor>>_ whose _X.509 certificate_ is being used for this assertion.
* The validator SHALL maintain one or more _<<_trust_list,trust lists>>_ which do not need to be the same as the _<<_trust_list,trust lists>>_ used to validate claim generator signatures as described in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_c2pa_signers++[Section 14.4.1, “C2PA Signers.”]
* The validator SHALL consider any v1 time-stamp as defined in link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_choosing_the_payload++[Section 10.3.2.5.2, “Choosing the payload”] to be invalid.

== Trust model

IMPORTANT: This section augments link:++https://c2pa.org/specifications/specifications/2.1/specs/C2PA_Specification.html#_trust_model++[Section 14, “Trust model,”] of the C2PA technical specification by adding additional trust signals related to the identity of _<<_actor,actors>>_ involved in creation of a _<<C2PA asset>>._ It does not replace any portion of the C2PA trust model.

=== What does trust mean?

_This section is non-normative._

This specification defines three distinct kinds of trust:

==== Technical trust

*Technical trust* exists if the following requirements are met to the satisfaction of the _<<_identity_assertion_consumer,identity assertion consumer>>:_

* Can I prove that the content I’m consuming was signed by a credential associated with a _<<_named_actor,named actor>>_ and that the content is unmodified from what the _<<_named_actor,named actor>>_ produced at the time it was signed?
* Can I trust that the identity signals in the credential point to a _<<_named_actor,named actor>>?_
* Do I trust that the identifier for the credential *issuer* is unique?

The *<<_identity_assertion,identity assertion>>* should be thought of primarily as providing a framework for establishing _technical trust_ between a _<<_named_actor,named actor>>_ and an _<<_identity_assertion_consumer,identity assertion consumer>>._

==== Governance trust

*Governance trust* exists if the following requirements are met to the satisfaction of the _<<_identity_assertion_consumer,identity assertion consumer>>:_

* Am I confident in how the credential(s) were issued to a _<<_named_actor,named actor>>?_ Do I understand the level of assurance offered by the credential issuer? Is it sufficient for me to accept the identity of the _<<_named_actor,named actor>>_ as valid and meaningful?
* Am I confident in how the credential(s) were managed and controlled by the _<<_named_actor,named actor>>,_ _<<credential_holder,credential holder>>,_ and issuer, and then used to sign the content I'm consuming?
* If the issuer is referenced on a _<<_trust_list,trust list>>,_ do I trust the governance of that _<<_trust_list,trust list>>?_ In other words, do I have confidence in the process by which this issuer was added to and has remained on the _<<_trust_list,trust list>>?_

Software tools supporting _<<_identity_assertion_consumer,identity assertion consumers>>_ can assist in establishing _governance trust_ by making well-informed choices about roots of trust.

==== Reputation trust

*Reputation trust* exists if the following requirements are met to the satisfaction of the _<<_identity_assertion_consumer,identity assertion consumer>>:_

* Am I confident that the _<<_named_actor,named actor>>_ will produce valuable content in good faith?
* Does the _<<_named_actor,named actor>>_ have a reputation and legitimacy that I can rely on?

While _reputation trust_ requires _technical trust_ and _governance trust_ to be established in order to evaluate it meaningfully, these criteria are largely subjective and thus outside the scope of this specification. Also, unlike _technical trust,_ the evaluation of _reputation trust_ is likely to evolve over time as the _<<_identity_assertion_consumer,identity assertion consumer>>_ gains experience with and learns more about the _<<_named_actor,named actor>>._

=== Technical trust introduction

_This section is non-normative._

The relationships required to establish technical trust are typically described using a _trust diamond_ as shown in the following diagram:

.Basic trust diamond
image::trust-model/basic-trust-diamond.drawio.svg[Basic trust triangle,width=430,height=250,align="center"]

The four roles depicted can each be performed by a human, organization, machine, or some combination thereof. A _governing authority_ sets the rules over the issuance of conformant identities from _credential issuers_ to _<<_credential_holder,credential holders>>_ and allows _credential issuers_ to appear on a _<<_trust_list,trust list>>_ after it satisfies the conformance of its rules within its governance framework. A _<<_credential_holder,credential holder>>_ establishes a relationship with a _credential issuer._ If the _issuer_ trusts the _<<_credential_holder,credential holder>>,_ it will then issue a digital credential which makes statements about the _<<_named_actor,named actor>>_ (which may or may not be the same _<<_actor,actor>>_ as the _<<_credential_holder,credential holder>>_) and is signed by the _issuer._

Later, the _<<_credential_holder,credential holder>>_ can then present this credential to a _verifier_ (also often known as a “relying party”). If the _verifier_ has an existing trust relationship with the _credential issuer,_ then the _verifier_ can choose to trust the credential, after checking that credential was issued by an _issuer_ appearing on the _<<_trust_list,trust list>>,_ and the statements made within it.

This pattern can be repeated if there is not a direct trust relationship between the _verifier_ and _issuer._ The _issuer_ itself might have a credential that is issued by another _issuer_ that is known to the _verifier_ as shown in the following diagram:

.Transitive trust triangle
image::trust-model/transitive-trust-triangle.drawio.svg[Transitive trust triangle,width=570,height=220,align="center"]

In this scenario, _issuer 2_ is playing a dual role as _<<_credential_holder,credential holder>>_ and _credential issuer._ The _verifier_ does not have a direct relationship with the issuer of the credentials that were presented (_issuer 2_). However, it can inspect _issuer 2’s_ credentials and find that they were issued by _issuer 1,_ with whom it does have a direct relationship. Based on the nature of that relationship, it may choose to extend *transitive trust* to _issuer 2_ and thus to the credential that _issuer 2_ issued.

Web browsers provide a well-known example of transitive trust. Browsers have direct relationships with relatively few root trust anchors. Those anchors, known as _root certificate authorities,_ in turn issue credentials to _certificate authorities_ who then issue credentials to individual web site operators who then sign the content presented to a browser. This pattern may be repeated with multiple layers of intermediate certificate authorities. The web browser evaluates this entire chain of credentials when deciding whether to present a web site as trusted or not.

=== Trust scenarios in identity assertion

The `signature` in an *<<_identity_assertion,identity assertion>>* could be considered as a new credential documenting the relationship between _<<_named_actor,named actor>>_ and _<<C2PA asset>>,_ which will be referred to in this section as an _asset-specific credential._

IMPORTANT: “Content Credential” is a trademarked term that refers to _<<_c2pa_manifest,C2PA Manifests>>_ and MUST NOT be used in reference to *<<_identity_assertion,identity assertion>>* signatures.

For each form of credential that an _<<_identity_asertion_consumer,identity assertion consumer>>_ is prepared to accept, it SHOULD maintain:

. a list of trust relationships that it is prepared to accept when interpreting any *<<_identity_assertion,identity assertion>>,* and
. one or more mechanisms to check for credentials that have been _<<_credential_revocation,revoked>>_ by the _issuer._

There are a few possible relationships between the implementation of the *<<_identity_assertion,identity assertion>>,* _<<_named_actor,named actor>>,_ and _credential issuer,_ as documented in the following subsections.

IMPORTANT: The trust decisions described in the scenarios should only be evaluated once the *<<_identity_assertion,identity assertion>>* and the signature material within have been successfully validated as described in xref:_validating_the_identity_assertion[xrefstyle=full].

The trust decision can result in one of three descriptions of the _<<_named_actor,named actor>>:_

* *Trusted:* The _<<_identity_asertion_consumer,identity assertion consumer>>_ can verify a trust relationship to the _<<_named_actor,named actor>>_ through its established roots of trust. The _<<_identity_asertion_consumer,identity assertion consumer>>_ found no evidence that the credential was _<<_credential_revocation,revoked>>_ at the time the *<<_identity_assertion,identity assertion>>* was created.
* *Well-formed:* The _<<_identity_asertion_consumer,identity assertion consumer>>_ can not verify a trust relationship to the _<<_named_actor,named actor>>._ The _<<_identity_asertion_consumer,identity assertion consumer>>_ found no evidence that the credential was _<<_credential_revocation,revoked>>_ at the time the *<<_identity_assertion,identity assertion>>* was created.
* *Revoked:* The credential used for signing the *<<_identity_assertion,identity assertion>>* had been _<<_credential_revocation,revoked>>_ at the time the *<<_identity_assertion,identity assertion>>* was created.

==== Named actor as issuer

In this scenario, the _<<_credential_holder,credential holder>>_ possesses a credential that describes the _<<_named_actor,named actor>>_ and is provisioned with the ability to generate digital signatures on the _<<_named_actor,named actor’s>>_ behalf.

This scenario is implicit in the X.509 certificate-based workflow as described in xref:_x_509_certificates_and_cose_signatures[xrefstyle=full]. Other credential types MAY also follow this scenario.

The _<<_credential_holder,credential holder>>_ uses this signature authority directly to generate the _asset-specific credential,_ as depicted in the following diagram, which is non-normative:

.Named actor as issuer
image::trust-model/named-actor-as-issuer.drawio.svg[Named actor as issuer,width=570,height=240,align="center"]

In this scenario, the _<<_identity_assertion_consumer,identity assertion consumer>>_ SHOULD make its trust decision based on the following predicates:

. Is there a direct trust relationship with the _<<_named_actor,named actor>>?_ If so, the *<<_identity_assertion,identity assertion>>* SHOULD be treated as *trusted.*
. Is there a transitive trust relationship with the _<<_named_actor,named actor>>_ via its _credential issuer?_ (In other words, does the _<<_identity_assertion_consumer,identity assertion consumer>>_ trust the _credential issuer_ to issue valid signature credentials?)
.. If so, was the _<<_named_actor,named actor’s>>_ credential _<<_credential_revocation,revoked>>_ at the time the *<<_identity_assertion,identity assertion>>* was signed? If so, the *<<_identity_assertion,identity assertion>>* SHOULD be treated as *revoked.*
.. If the transitive trust relationship exists and the credential has not been _<<_credential_revocation,revoked>>,_ the *<<_identity_assertion,identity assertion>>* SHOULD be treated as *trusted.*
. If neither relationship can be demonstrated, the *<<_identity_assertion,identity assertion>>* SHOULD be treated as *well-formed.*

IMPORTANT: Any available information about credential _<<_credential_revocation,revocation>>_ SHOULD be included in the _<<_identity_assertion_consumer,identity assertion consumer’s>>_ report about the *<<_identity_assertion,identity assertion>>* regardless of *trusted* or *untrusted* status.

NOTE: The direct trust relationship case is possible, but relatively uncommon.

==== Named actor without signature authority

In this scenario, the _<<_credential_holder,credential holder>>_ possesses a credential that describes the _<<_named_actor,named actor>>_ but does not have the ability to generate digital signatures on the _<<_named_actor,named actor’s>>_ behalf.

In this scenario, the hardware or software implementation that is generating the *<<_identity_assertion,identity assertion>>* MAY request a summary of the _<<_named_actor,named actor’s>>_ credential from the _<<_credential_holder,credential holder>>,_ and gather that information into the *<<_identity_assertion,identity assertion>>,* which it will then sign using its own credentials.

.Example using W3C verifiable credentials
[sidebar]
****
This example, which is non-normative, depicts a possible workflow for this scenario. In this scenario, the _<<_credential_holder,credential holder>>_ wishes to use a W3C verifiable credential held in a wallet to generate an *<<_identity_assertion,identity assertion>>* on behalf of the credential’s _<<_named_actor,named actor>>._

In this example, the wallet is prepared to selectively disclose portions of the credential via W3C verifiable presentation, but can neither reveal the entire credential nor issue other forms of signature.

[mermaid,width=100%]
....
sequenceDiagram
    participant G as Identity assertion generator
    participant W as Wallet
    participant H as Credential holder

    Note right of G: Create signer_payload

    G->>W: Presentation request<br>including signer_payload
    W->>H: Request consent for presentation
    H->>W: Consent granted
    W->>G: Verifiable presentation

    Note right of G: Generate new asset-specific<br>credential using VP content
....

****

In this scenario, the _issuer_ of the _asset-specific credential_ is not the _<<_credential_holder,credential holder>>_ but the _<<_actor,actor>>_ that is generating the *<<_identity_assertion,identity assertion>>,* as depicted in the following diagram, which is non-normative:

.Named actor without signature authority
image::trust-model/no-signature-authority.drawio.svg[Named actor without signature authority,width=570,height=320,align="center"]

In this scenario, the _<<_identity_assertion_consumer,identity assertion consumer>>_ SHOULD make its trust decision based on the following predicates:

. Does the _<<_identity_assertion_consumer,identity assertion consumer>>_ trust the _<<_identity_assertion_generator,identity assertion generator>>_ to request a credential summary from the _<<_credential_holder,credential holder>>_ and accurately reflect that credential summary into the *<<_identity_assertion,identity assertion>>?*
.. Is there a direct trust relationship with the _<<_identity_assertion_generator,identity assertion generator>>?_ If so, proceed to step 2.
.. Is there a transitive trust relationship with the _<<_identity_assertion_generator,identity assertion generator>>_ via its _credential issuer?_ (In other words, does the _<<_identity_assertion_consumer,identity assertion consumer>>_ trust the _<<_identity_assertion_generator,identity assertion generator’s>>_ _credential issuer_ to issue valid signature credentials?)
.. If so, was the _<<_identity_assertion_generator,identity assertion generator’s>>_ credential _<<_credential_revocation,revoked>>_ at the time the *<<_identity_assertion,identity assertion>>* was signed? If so, do not proceed. The *<<_identity_assertion,identity assertion>>* SHOULD be treated as *revoked.*
.. If the transitive trust relationship exists and the credential has not been _<<_credential_revocation,revoked>>,_ proceed to step 2.
.. If neither relationship can be demonstrated, do not proceed. The *<<_identity_assertion,identity assertion>>* SHOULD be treated as *well-formed.*
. Does the _<<_identity_assertion_consumer,identity assertion consumer>>_ trust the _<<_named_actor,named actor’s>> credential issuer_ to issue valid credentials?
.. Is there a direct trust relationship with the _<<_named_actor,named actor’s>> credential issuer?_ If so, proceed to step 3.
.. Is there a transitive trust relationship with the _<<_named_actor,named actor’s>> credential issuer_ via its _credential issuer?_ (In other words, does the _<<_identity_assertion_consumer,identity assertion consumer>>_ trust the _<<named_actor,named actor’s>> credential issuer_ to issue valid credentials?) If so, proceed to step 3.
.. If neither relationship can be demonstrated, do not proceed. The *<<_identity_assertion,identity assertion>>* SHOULD be treated as *well-formed.*
. Was the _<<_named_actor,named actor’s>>_ credential _<<_credential_revocation,revoked>>_ at the time the *<<_identity_assertion,identity assertion>>* was signed?
.. If so, the *<<_identity_assertion,identity assertion>>* SHOULD be treated as *revoked.*
.. If no such _<<_credential_revocation,revocation>>_ has been issued, the *<<_identity_assertion,identity assertion>>* SHOULD be treated as *trusted.*

IMPORTANT: Any available information about _<<_credential_revocation,credential revocation>>_ SHOULD be included in the _<<_identity_assertion_consumer,identity assertion consumer’s>>_ report about the *<<_identity_assertion,identity assertion>>* regardless of *trusted* or *untrusted* status.

=== Threats to trust model

_This section is non-normative._

This section enumerates a number of potential attacks on the *<<_identity_assertion,identity assertion>>* trust model. If concrete guidance to mitigate or prevent a specific attack is available, that guidance should be incorporated as specific normative requirements elsewhere in this specification and referenced here.

==== Replay attacks

An attacker could attempt to extract a valid *<<_identity_assertion,identity assertion>>* out of one _<<_c2pa_asset,C2PA asset>>_ and embed it in a new _<<_c2pa_asset,C2PA asset>>_ of an attacker's choosing without causing a validation error. This scenario could allow an attacker to falsely attribute the new _<<_c2pa_asset,C2PA asset>>_ to a victim’s identity without their consent or knowledge. If the attacker’s _<<_c2pa_asset,C2PA asset>>_ is controversial or illegal, then falsely attributing it to a victim’s identity could result in severe consequences for the victim. The system must ensure that an attacker can not apply an existing *<<_identity_assertion,identity assertion>>* to a different _<<_c2pa_asset,C2PA asset>>._

To prevent this attack, we require that a valid *<<_identity_assertion,identity assertion>>* contain a `signer_payload.referenced_assertions` which includes a _<<_hard_binding,hard binding>>_ assertion that properly describes the _<<_c2pa_asset,C2PA asset>>._ A compliant _<<_identity_assertion_consumer,identity assertion consumer>>_ should detect that the _<<_hard_binding,hard binding>>_ assertion referenced by the original *<<_identity_assertion,identity assertion>>* does not match the attacker’s _<<_c2pa_asset,C2PA asset>>_ and fail validation.

==== Parsing and validation errors

Any content including, but not limited to the _<<_named_actor,named actor’s>>_ identity, could be subject to a number of parsing or validation attacks:

* *Injection of code* (HTML, JavaScript, etc.) into a text field so that the attacker can attempt to control what is displayed to the end user. _Does the specification support markup in the text fields? Should all fields be considered unicode strings?_
* *Text fields of excessive length:* These can cause buffer overflows or could be an attempt to "push" trusted UI indicators out of the rendered view of the user. _Should the specification place an upper bound of the length of given fields?_
* *Injection of special characters:* These can be truncation attacks. For instance, if the UI parser is written in C, then an attacker might try to inject a null byte to cause discrepancies in the code about what should be displayed. _Are there any special characters necessitated by the specification that need to be escaped before being placed into the text field of an assertion?_

The effectiveness of such attacks will necessarily be dependent on the language and other related development tooling in use for any given implementation. Beyond reminding implementers that parsing and validation errors are a likely attack surface, it is outside the scope of this specification to provide language-specific guidance.

==== Name collisions, homoglyph attacks, and typo-squatting attacks

An attacker could make use of visually-similar Unicode characters to mislead an end user into accepting a mistaken assertion of identity on behalf of a specific _<<_named_actor,named actor>>._ Such attacks are common in phishing and impersonation attacks conducted on domain names and social media.

Similarly, it is likely that two or more _<<_named_actor,named actors>>_ may legitimately have the same or very similar names. Whether legitimate or not, similar names may cause confusion among _<<_identity_assertion_consumer,identity assertion consumers>>_ absent other signals that disambiguate specific individuals or organizations. If anonymous identities are supported, _<<_identity_assertion,identity assertions>>_ should also contain signals to disambiguate between anonymous identities.

IMPORTANT: The Creator Assertions Working Group supports the principle of link:https://www.icann.org/ua[Universal Acceptance as described by ICANN]. No mitigation for the attacks described in this section should result in preferential treatment for identifiers in any language or script system over any other language or script system.

Implementers are encouraged to apply one or more of the following approaches to mitigate this potential attack:

* Credential issuers are encouraged to verify proposed names carefully to avoid malicious use of names. Intermediate authorities (_<<_trust list,trust lists>>,_ intermediate CAs, etc.) are encouraged to require such verification as part of their governance terms.
* Software tools that support _<<_identity_assertion_consumer,identity assertion consumers>>_ are encouraged to maintain a list of trust anchors that have well-established governance terms designed to avoid the inclusion of inadvertently or maliciously misleading identity credentials and to reference those roots of trust in their user experience.
* Software tools that support _<<_identity_assertion_consumer,identity assertion consumers>>_ are encouraged to maintain lists of known _<<_named_actor,named actors>>_ via unique identifiers available with each credential type rather than the human-readable display names.
* Software tools that support _<<_identity_assertion_consumer,identity assertion consumers>>_ are encouraged to make visible the evaluation of an identity assertion as trusted, well-formed, or invalid.
* Software tools that support _<<_identity_assertion_consumer,identity assertion consumers>>_ are encouraged to display additional detail about the _<<_named_actor,named actor>>,_ such as the unique identifiers behind the credential, upon user request.
* Future versions of this specification will likely allow linking independent verifiable trust signals (social accounts, web sites, etc.). As those become available, _<<_named_actor,named actors>>_ are encouraged to include those signals and _<<_identity_assertion_consumer,identity assertion consumers>>_ are encouraged to verify those signals.

==== Revocation of credential

There are numerous scenarios which may result in the credential issued to a _<<_credential_holder,credential holder>>_ being _<<_credential_revocation,revoked>>._ Some are adverse, such as credential compromise or acting in bad faith. Other scenarios are routine, such as changes to the name, address, or other identifying information contained within the credentials.

The _<<_identity_assertion_consumer,identity assertion consumer>>_ should make a best effort to verify the status of the credential as of the time of *<<_identity_assertion,identity assertion>>* creation. The exact mechanism will vary based on the credential type and will be specified in the appropriate subsection of xref:_credentials_signatures_and_validation_methods[xrefstyle=full]. If a credential is found to be _<<_credential_revocation,revoked>>_ at that time, this information should be prominently displayed in any user experience regarding the *<<_identity_assertion,identity assertion>>.* Absent specific information as to the cause for _<<_credential_revocation,revocation,>>_ a _<<_identity_assertion_consumer,identity assertion consumer>>_ should not assume that a _<<_credential_revocation,revocation>>_ is an indication of an adverse event.

Software tools that support _<<_identity_assertion_consumer,Identity assertion consumers>>_ are encouraged to be mindful of harms or risks – such as generating network traffic that may indicate interest in particular content – that may accrue to the _<<_identity_assertion_consumer,identity assertion consumer>>_ in the process of making online inquiries about such status.

==== Compromise of private key material

In practice, the _<<_credential_holder,credential holder’s>>_ signing keys will be issued to systems that perform *<<_identity_assertion,identity assertion>>* signing operations. These systems may make these operations available to end users and/or be deployed to user-owned platforms (e.g., mobile phones). Issuance or disclosure of signing keys to malicious actors enables attackers to create claim signatures on arbitrary assets using the compromised identity. The resulting *<<_identity_assertion,identity assertions>>* will be valid in terms of the *<<_identity_assertion,identity assertion>>* specification, but effectively allow for spoofing identity.

It is therefore important that systems that manage *<<_identity_assertion,identity assertion>>* signing keys adhere to security and key management best practices. This includes leveraging platform-specific features (e.g., hardware security modules and cloud key management services), minimizing key reuse, and _<<_credential_revocation,revoking>>_ keys when compromise is suspected. For more information on key management, see the link:https://csrc.nist.gov/Projects/Key-Management/Key-Management-Guidelines[NIST Key Management Guidelines].

Some *<<_identity_assertion,identity assertion>>* generation and signing systems may be exposed to untrusted users. Exploitation or misuse of these systems may allow attackers to create *<<_identity_assertion,identity assertion>>* signatures on arbitrary assets using identities provided by the system. The resulting *<<_identity_assertion,identity assertions>>* will be valid in terms of the *<<_identity_assertion,identity assertion>>* specification, but effectively allow for spoofing identity. The impact of such an attack may be amplified if identities are shared between users, and/or if the attack goes undetected for an extended period of time.

*<<_identity_assertion,Identity assertion>>* generation and signing systems should consider industry best practices for information security, secure development and operation, and anti-abuse practices, including leveraging available platform-specific features for deployment (e.g., link:https://developer.android.com/training/safetynet[Android SafetyNet], link:https://developer.apple.com/documentation/devicecheck[Apple DeviceCheck and AppAttest]).

Capture devices, such as non-smartphone cameras, often do not have a mechanism for restricting access to specific users. It is recommended that such devices should not hold credentials for _<<_named_actor,named actors>>_ and should not generate *<<_identity_assertion,identity assertion>>* unless they can access more secure credential-access mechanisms such as a digital wallet.

==== Tampering with identity assertion content

An attacker could attempt to alter the content of an *<<_identity_assertion,identity assertion>>* to substitute different credentials or alter the attestations included in `signer_payload` in order to create a misleading of the _<<_named_actor,named actor>>_ or the _<<_c2pa_asset,C2PA asset>>._

A compliant _<<_identity_assertion_consumer,identity assertion consumer>>_ should validate the `signature` field of the *<<_identity_assertion,identity assertion>>.* If the content of `signer_payload` has been altered, the signature should not match and the _<<_identity_assertion_consumer,identity assertion consumer>>_ should fail validation in that case.

The signature from the _<<_claim_generator,claim generator>>_ provides an additional level of tamper evidence. In the event an attacker substitutes a new *<<_identity_assertion,identity assertion>>* which contains a new signature that is valid, the hash reference from the _<<_c2pa_claim,C2PA claim>>_ should still mismatch. A compliant _<<_c2pa_manifest_consumer,C2PA Manifest Consumer>>_ should fail validation in that case. When validation of a _<<_c2pa_manifest,C2PA Manifest>>_ has failed, a compliant _<<_identity_assertion_consumer,identity assertion consumer>>_ should not attempt to interpret the content of any *<<_identity_assertion,identity assertion>>* in that _<<_c2pa_manifest,C2PA Manifest>>._

==== Re-signing by an adversarial claim generator

An attacker could take a valid _<<_c2pa_asset,C2PA asset>>_ and create a new _<<C2PA Manifest>>_ with a new signature from a new _<<_claim_generator,claim generator>>_ that alters the context that was anticipated by the original _<<_credential_holder,credential holder>>_ when signing the *<<_identity_assertion,identity assertion>>.*

[#new-context-adversarial-claim-generator]
.New context introduced by adversarial claim generator
[example]
====
This diagram builds upon xref:trust-signal-scope-one-ia[xrefstyle=full], to show how an adversarial _<<_claim_generator,claim generator>>_ could alter the context for the *<<_identity_assertion,identity assertion>>.*

.Re-contextualization attack
image::adversarial-claim-generator/adversarial-trust-bubbles.drawio.svg[Adversarial claim generator example,width=520,height=400,align="center"]

In this example, the attacker has used a new _<<_claim_generator,claim generator’s>>_ signature to re-contextualize the original _<<_c2pa_asset,C2PA asset>>_ without the original _<<_credential_holder,credential holder’s>>_ knowledge.

[IMPORTANT]
.Scope of attack surface
======
In this scenario, the attacker _could:_

* Remove any _<<_c2pa_assertion,C2PA assertions>>_ not referenced in the *<<_identity_assertion,identity assertion>>* (A3 in this example).
* Introduce new _<<_c2pa_assertion,C2PA assertions>>_ (A4 and A5 in this example).
* Substitute a new _<<_claim_generator,claim generator>>_ that is unknown to the _<<_credential_holder,credential holder>>._

The attacker could not:

* Modify the asset content (because the _<<_hard_binding,hard binding>>_ assertion would not match the new asset).
* Modify any of the _<<_c2pa_assertion,C2PA assertions>>_ referenced in the *<<_identity_assertion,identity assertion>>* (A1 or A2 in this example).
======
====

A _<<_credential_holder,credential holder>>_ can prevent these attacks by using one or more of the following optional mechanisms in `signer_payload` which are intended to limit the content of the enclosing _<<C2PA Manifest>>:_

* `expected_partial_claim`, which describes the content of the expected _<<C2PA claim>>_ in which the *<<_identity_assertion,identity assertion>>* appears.
* `expected_claim_generator`, which describes the X.509 certificate of the expected _<<C2PA claim generator>>._
* `expected_countersigners`, which describes the signing credential(s) of the expected _<<_named_actor,named actors>>_ for other *<<_identity_assertion,identity assertions>>* in the same _<<C2PA Manifest>>._

See xref:_overview[xrefstyle=full], for complete description of these mechanisms.

== User experience

_This section is non-normative._

=== Approach

The Creator Assertions Working Group intends, in a forthcoming document, to provide clear recommendations and guidance for implementers of identity-based provenance user experiences (UX). Similar to the C2PA’s link:https://c2pa.org/specifications/specifications/2.0/ux/UX_Recommendations.html[User experience guidance for implementers], CAWG UX recommendations aim to define best practices for presenting CAWG identity assertions within a _<<_c2pa_manifest,C2PA Manifest>>._ The recommendations strive to describe standard, readily-recognizable experiences that:

* provide _<<named_actors,named actors>>_ a means to express *<<_identity_assertion,identity assertions>>* about a _<<_c2pa_asset,C2PA asset>>,_ and
* provide _<<_identity_assertion_consumer,identity assertion consumers>>_ with additional information about the _<<_c2pa_asset,C2PA asset>>_ they are experiencing, thereby empowering them to understand who is involved in its creation.

CAWG UX recommendations should adhere to the same principles and levels of information disclosure outlined in the link:https://c2pa.org/specifications/specifications/2.0/ux/UX_Recommendations.html[C2PA UX Guidance].  

=== Public review, feedback, and evolution

Developing these recommendations is an ongoing process that involves diverse stakeholders, with the results balancing uniformity and familiarity with utility and flexibility for users across contexts, platforms, and devices. Feedback, review, user testing, and ongoing evolution are key requirements for success. The recommendations will therefore be an evolving document, informed by real-world experiences deploying CAWG-enabled _<<_c2pa_manifest,C2PA Manifests>>_ across a wide variety of applications and scenarios. These recommendations will be provided as a companion document.

include::partial$version-history.adoc[]
