== Version history

IMPORTANT: This version history reflects changes to this document made while in private review. It will be removed and reset when the spec becomes public.

*27 November 2023*

* Initial private review draft.

*29 November 2023*

* Added this version history section.

*30 November 2023*

* Minor proofreading edits.

*01 December 2023*

* Replace partial claim mechanism with list of assertions. Significant updates to:
** xref:_placeholder_assertion[xrefstyle=full]
** xref:_assertion_definition[xrefstyle=full]
** xref:_creating_the_identity_assertion[xrefstyle=full]
** xref:_validation_method[xrefstyle=full]
* Identify versions of normative reference documents.
** xref:_normative_references[xrefstyle=full]

*02 December 2023*

* Add _<<C2PA claim generator>>_ to the glossary and cross-reference it through out the document.
** xref:_concepts_adapted_from_c2pa_technical_specification[xrefstyle=full]
* Minor proofreading edits.

*03 December 2023*

* Add a TO DO item in xref:_trust_model[xrefstyle=full].
* Proofreading: Correct references to distributed identifiers to _decentralized identifiers._
* Incorporate additional review feedback.

*13 December 2023*

* Add xref:_conceptual_overview[xrefstyle=full]
* New wording regarding intended meaning of credential holder’s signature. Changes to:
** xref:_conceptual_overview[xrefstyle=full]
* Removed wording carried over from C2PA 1.3 spec regarding interpretation of verifiable credential.
* Rewrite xref:_w3c_verifiable_credentials_and_verifiable_presentations[xrefstyle=full].
* Add xref:_content_binding[xrefstyle=full] to glossary

*15 December 2023*

* Minor proofreading edits.
* Rename `assertions` field in identity assertion to `referenced_assertions`; also introduce the term _referenced assertions_ for the list of assertions signed by the _<<_credential_subject,credential subject>>._
